
--- PARA QUE COMPILE - BDVEMPP.ENCRIPTAR_SHA1 COMPILE;
GRANT EXECUTE ON DBMS_CRYPTO TO BDVEMPP;


--- PARA QUE COMPILE - BDVEMPP.MTTO_PART_RT COMPILE;

GRANT ADVISOR TO BDVEMPP;
GRANT CREATE ANY INDEX TO BDVEMPP;
GRANT CREATE LIBRARY TO BDVEMPP;
GRANT CREATE MATERIALIZED VIEW TO BDVEMPP;
GRANT CREATE PROCEDURE TO BDVEMPP;
GRANT CREATE PUBLIC DATABASE LINK TO BDVEMPP;
GRANT CREATE PUBLIC SYNONYM TO BDVEMPP;
GRANT CREATE SEQUENCE TO BDVEMPP;
GRANT CREATE SESSION TO BDVEMPP;
GRANT CREATE SYNONYM TO BDVEMPP;
GRANT CREATE TABLE TO BDVEMPP;
GRANT CREATE TRIGGER TO BDVEMPP;
GRANT CREATE TYPE TO BDVEMPP;
GRANT CREATE VIEW TO BDVEMPP;
GRANT DEBUG ANY PROCEDURE TO BDVEMPP;
GRANT DEBUG CONNECT SESSION TO BDVEMPP;
GRANT DROP PUBLIC DATABASE LINK TO BDVEMPP;
GRANT EXECUTE ANY PROCEDURE TO BDVEMPP;
GRANT SELECT ANY SEQUENCE TO BDVEMPP;
GRANT SELECT ANY TABLE TO BDVEMPP;
GRANT UNLIMITED TABLESPACE TO BDVEMPP;

-- 1 Tablespace Quota for BDVEMPP
ALTER USER BDVEMPP QUOTA UNLIMITED ON DATA;

-- 6 Object Privileges for BDVEMPP
GRANT SELECT ON SYS.DBA_DIRECTORIES TO BDVEMPP;
GRANT SELECT ON SYS.DBA_TAB_PARTITIONS TO BDVEMPP;
GRANT SELECT ON SYS.DBA_TAB_SUBPARTITIONS TO BDVEMPP;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO BDVEMPP;
GRANT EXECUTE ON SYS.DBMS_DATAPUMP TO BDVEMPP;
GRANT READ, WRITE ON DIRECTORY EXPORT TO BDVEMPP;



