ALTER PROCEDURE BDVEMPP.PR_EMP_REG_COLA_TRANS COMPILE;

ALTER PROCEDURE BDVEMPP.ENCRIPTAR_SHA1 COMPILE;

ALTER PROCEDURE BDVEMPP.PR_EMP_EMCRIPTAR_SHA1 COMPILE;

ALTER PROCEDURE BDVEMPP.PR_CAMBIA_CLAVE COMPILE;

ALTER PROCEDURE BDVEMPP.PR_CREA_NUEVA_CLAVE COMPILE;

ALTER PROCEDURE BDVEMPP.PR_EMP_CARGAR_INF_TOKEN COMPILE;

ALTER PROCEDURE BDVEMPP.PR_GENERA_CLAVE COMPILE;

ALTER PROCEDURE BDVEMPP.PR_REINICIO_CLAVE COMPILE;

ALTER PROCEDURE BDVEMPP.PR_BNET_ENVIA_MAIL_TOKEN COMPILE;

ALTER PROCEDURE BDVEMPP.MTTO_PART_RT COMPILE;

DROP PROCEDURE SYSTEM.PR_EMP_REG_COLA_TRANS;
