
**Rollback_Rename_Tabla_Posting_PRD


POSTING a POSTING_NEW
01. Rename_Tabla_Posting_new
02. Rename_Index_Table_Posting_new
03. Rename_Constraint_Table_Posting_new
04. Rename_Trigger_Table_Posting_new

POSTING_BK a POSTING
05. Rename_Tabla_Posting
06. Rename_Index_Table_Posting
07. Rename_Constraint_Table_Posting
08. Rename_Trigger_Table_Posting


@01_rename_table_posting_new.sql
@02_rename_index_table_posting_new.sql
@03_rename_constraint_table_posting_new.sql
@04_rename_trigger_table_posting_new.sql

@05_rename_table_posting.sql
@06_rename_index_table_posting.sql
@07_rename_constraint_table_posting.sql
@08_rename_trigger_table_posting.sql



*************************************************************************
************************* POSTING a POSTING_NEW *************************
*************************************************************************

01. Rename_Tabla_Posting_new

vi 01_rename_table_posting_new.sql

	spool 01_rename_table_posting_new.lst
	set timi on time on
	set line 240
	
	ALTER TABLE TX.POSTING RENAME TO POSTING_NEW;
	
	spool off;



02. Rename_Index_Table_Posting_new

vi 02_rename_index_table_posting_new.sql

	spool 02_rename_index_table_posting_new.lst
	set timi on time on
	set line 240
	
	ALTER INDEX TX.IDX_POSTING_ACCOUNTDAY RENAME TO IDX_POSTING_ACCOUNTDAY_NEW;
	ALTER INDEX TX.PK_POSTING RENAME TO PK_POSTING_NEW;
	
	spool off;


03. Rename_Constraint_Table_Posting_new

vi 03_rename_constraint_table_posting_new.sql

	spool 03_rename_constraint_table_posting_new.lst
	set timi on time on
	set line 240
	
	ALTER TABLE TX.POSTING_NEW RENAME CONSTRAINT FK_POSTING_ACCOUNT TO FK_POSTING_ACCOUNT_NEW;
	ALTER TABLE TX.POSTING_NEW RENAME CONSTRAINT CKC_AMT_POSTING TO CKC_AMT_POSTING_NEW;
	ALTER TABLE TX.POSTING_NEW RENAME CONSTRAINT CKC_BASEAMT_POSTING TO CKC_BASEAMT_POSTING_NEW;
	ALTER TABLE TX.POSTING_NEW RENAME CONSTRAINT SYS_C0011507 TO SYS_C0011507_NEW;
	ALTER TABLE TX.POSTING_NEW RENAME CONSTRAINT SYS_C0011508 TO SYS_C0011508_NEW;
	ALTER TABLE TX.POSTING_NEW RENAME CONSTRAINT SYS_C0011509 TO SYS_C0011509_NEW;
	ALTER TABLE TX.POSTING_NEW RENAME CONSTRAINT SYS_C0011510 TO SYS_C0011510_NEW;
	ALTER TABLE TX.POSTING_NEW RENAME CONSTRAINT SYS_C0011511 TO SYS_C0011511_NEW;
	ALTER TABLE TX.POSTING_NEW RENAME CONSTRAINT SYS_C0011512 TO SYS_C0011512_NEW;
	ALTER TABLE TX.POSTING_NEW RENAME CONSTRAINT SYS_C0011513 TO SYS_C0011513_NEW;
	ALTER TABLE TX.POSTING_NEW RENAME CONSTRAINT SYS_C0011514 TO SYS_C0011514_NEW;
	ALTER TABLE TX.POSTING_NEW RENAME CONSTRAINT SYS_C0011515 TO SYS_C0011515_NEW;
	ALTER TABLE TX.POSTING_NEW RENAME CONSTRAINT SYS_C0011516 TO SYS_C0011516_NEW;
	ALTER TABLE TX.POSTING_NEW RENAME CONSTRAINT SYS_C0011517 TO SYS_C0011517_NEW;
	ALTER TABLE TX.POSTING_NEW RENAME CONSTRAINT PK_POSTING TO PK_POSTING_NEW;
	ALTER TABLE TX.POSTING_NEW RENAME CONSTRAINT FK_POSTING_ENTRYPART TO FK_POSTING_ENTRYPART_NEW;
	ALTER TABLE TX.POSTING_NEW RENAME CONSTRAINT FK_POSTING_INSTITUTION TO FK_POSTING_INSTITUTION_NEW;
	ALTER TABLE TX.POSTING_NEW RENAME CONSTRAINT FK_POSTING_TRAN TO FK_POSTING_TRAN_NEW;
	ALTER TABLE TX.POSTING_NEW RENAME CONSTRAINT UNQ_POSTING_ACCOUNTDAY TO UNQ_POSTING_ACCOUNTDAY_NEW;
	
	spool off;


04. Rename_Trigger_Table_Posting_new

vi 04_rename_trigger_table_posting_new.sql

	spool 04_rename_trigger_table_posting_new.lst
	set timi on time on
	set line 240
	
	ALTER TRIGGER TX.TBIR_POSTING RENAME TO TBIR_POSTING_NEW;
	
	spool off;




*************************************************************************
************************* POSTING_BK a POSTING **************************
*************************************************************************

05. Rename_Tabla_Posting

vi 05_rename_table_posting.sql

	spool 01_rename_table_posting.lst
	set timi on time on
	set line 240
	
	ALTER TABLE TX.POSTING_BK RENAME TO POSTING;
	
	spool off;



06. Rename_Index_Table_Posting

vi 06_rename_index_table_posting.sql

	spool 02_rename_index_table_posting.lst
	set timi on time on
	set line 240
	
	ALTER INDEX TX.IDX_POSTING_ACCOUNTDAY_BK RENAME TO IDX_POSTING_ACCOUNTDAY;
	ALTER INDEX TX.PK_POSTING_BK RENAME TO PK_POSTING;
	
	spool off;


07. Rename_Constraint_Table_Posting

vi 07_rename_constraint_table_posting.sql

	spool 03_rename_constraint_table_posting.lst
	set timi on time on
	set line 240
	
	ALTER TABLE TX.POSTING RENAME CONSTRAINT FK_POSTING_ACCOUNT_BK TO FK_POSTING_ACCOUNT;
	ALTER TABLE TX.POSTING RENAME CONSTRAINT CKC_AMT_POSTING_BK TO CKC_AMT_POSTING;
	ALTER TABLE TX.POSTING RENAME CONSTRAINT CKC_BASEAMT_POSTING_BK TO CKC_BASEAMT_POSTING;
	ALTER TABLE TX.POSTING RENAME CONSTRAINT SYS_C0011507_BK TO SYS_C0011507;
	ALTER TABLE TX.POSTING RENAME CONSTRAINT SYS_C0011508_BK TO SYS_C0011508;
	ALTER TABLE TX.POSTING RENAME CONSTRAINT SYS_C0011509_BK TO SYS_C0011509;
	ALTER TABLE TX.POSTING RENAME CONSTRAINT SYS_C0011510_BK TO SYS_C0011510;
	ALTER TABLE TX.POSTING RENAME CONSTRAINT SYS_C0011511_BK TO SYS_C0011511;
	ALTER TABLE TX.POSTING RENAME CONSTRAINT SYS_C0011512_BK TO SYS_C0011512;
	ALTER TABLE TX.POSTING RENAME CONSTRAINT SYS_C0011513_BK TO SYS_C0011513;
	ALTER TABLE TX.POSTING RENAME CONSTRAINT SYS_C0011514_BK TO SYS_C0011514;
	ALTER TABLE TX.POSTING RENAME CONSTRAINT SYS_C0011515_BK TO SYS_C0011515;
	ALTER TABLE TX.POSTING RENAME CONSTRAINT SYS_C0011516_BK TO SYS_C0011516;
	ALTER TABLE TX.POSTING RENAME CONSTRAINT SYS_C0011517_BK TO SYS_C0011517;
	ALTER TABLE TX.POSTING RENAME CONSTRAINT PK_POSTING_BK TO PK_POSTING;
	ALTER TABLE TX.POSTING RENAME CONSTRAINT FK_POSTING_ENTRYPART_BK TO FK_POSTING_ENTRYPART;
	ALTER TABLE TX.POSTING RENAME CONSTRAINT FK_POSTING_INSTITUTION_BK TO FK_POSTING_INSTITUTION;
	ALTER TABLE TX.POSTING RENAME CONSTRAINT FK_POSTING_TRAN_BK TO FK_POSTING_TRAN;
	ALTER TABLE TX.POSTING RENAME CONSTRAINT UNQ_POSTING_ACCOUNTDAY_BK TO UNQ_POSTING_ACCOUNTDAY;
	
	spool off;


08. Rename_Trigger_Table_Posting

vi 08_rename_trigger_table_posting.sql

	spool 04_rename_trigger_table_posting.lst
	set timi on time on
	set line 240
	
	ALTER TRIGGER TX.TBIR_POSTING_BK RENAME TO TBIR_POSTING;
	
	spool off;