CREATE OR REPLACE PROCEDURE SIGEFIC.PR_GET_REPORTE_REMESA3(
    P_FECHA_DESDE IN VARCHAR,
    P_FECHA_HASTA IN VARCHAR,
    COD_RET   OUT VARCHAR2,
    DE_CODRET OUT VARCHAR2,
    SALIDA OUT SYS_REFCURSOR)   
IS 
V_FECHA_DESDE          VARCHAR(15);
V_FECHA_HASTA          VARCHAR(15);
V_FECHA_DESDE_VACIO    EXCEPTION;
V_FECHA_HASTA_VACIO    EXCEPTION;
BEGIN 
    CASE
        WHEN P_FECHA_DESDE = '' OR P_FECHA_DESDE IS NULL THEN
            RAISE V_FECHA_DESDE_VACIO;
        ELSE
            V_FECHA_DESDE := UPPER(P_FECHA_DESDE);
    END CASE;

    CASE
        WHEN P_FECHA_HASTA = '' OR P_FECHA_HASTA IS NULL THEN
            RAISE V_FECHA_HASTA_VACIO;
        ELSE
            V_FECHA_HASTA := UPPER(P_FECHA_HASTA);
    END CASE;

    OPEN SALIDA FOR 
    SELECT 
        TO_CHAR(MR.FECHA_CREACION, 'dd/mm/yyyy HH:mi:ss AM') FECHA_OPER,
        SF.REFERENCIA REFERENCIA_DE_PAGO,
        UPPER(SF.RESULTADO) ESTATUS,
        TRIM(TO_CHAR(MR.MONTO_TOTAL, '999G999G999G999G999G999G990D99')) MONTO_ORIGEN,
        TRIM(TO_CHAR(MR.MONTO_AUTORIZADOR, '999G999G999G999G999G999G990D99')) MONTO_AUTORIZADOR,
        TRIM(TO_CHAR(MR.MONTO_PROVEEDOR, '999G999G999G999G999G999G990D99')) MONTO_RECIBIDO_CHINCHIN,
        TRIM(TO_CHAR(MR.MONTO_COMISION_BDV, '999G999G999G999G999G999G990D99')) COMISION_BDV,
        TRIM(TO_CHAR(MR.MONTO_COMISION_PROV, '999G999G999G999G999G999G990D99')) COMISION_CHINCHIN,
        TRIM(TO_CHAR(MR.MONTO_TOTAL_REMESA, '999G999G999G999G999G999G990D99')) MONTO_REMESA
    FROM SIGEFIC.SIF_MOVIMIENTOS SF
    LEFT JOIN SIGEFIC.MOVIMIENTO_REMESA MR ON MR.REFERENCIA_PAGO = SF.REFERENCIA
    WHERE 
    SF.FECHA_TRANSACCION BETWEEN P_FECHA_DESDE AND P_FECHA_HASTA
    AND SF.PRODUCTO = '700101'
    ;
    
    COD_RET := '1000';
    DE_CODRET := 'CONSULTA EXITOSA';

EXCEPTION
    WHEN V_FECHA_DESDE_VACIO THEN 
        COD_RET := '9991';
        DE_CODRET := 'FECHA DESDE NO PUEDE SER VACIO';
    WHEN V_FECHA_HASTA_VACIO THEN 
        COD_RET := '9992';
        DE_CODRET := 'FECHA HASTA NO PUEDE SER VACIO';
    WHEN NO_DATA_FOUND THEN
        COD_RET := '9993';
        DE_CODRET := 'DATOS NO ENCONTRADOS';
    WHEN OTHERS THEN
        COD_RET     := '9999';
        DE_CODRET   := SUBSTR (SQLCODE || '  ' || SQLERRM, 1, 100); 
END;
/