ALTER DATABASE ADD LOGFILE THREAD 1 GROUP 4 ('+REDO01_STOKEN','+REDO02_STOKEN') SIZE 2048M;
ALTER DATABASE ADD LOGFILE THREAD 1 GROUP 5 ('+REDO01_STOKEN','+REDO02_STOKEN') SIZE 2048M;
ALTER DATABASE ADD LOGFILE THREAD 1 GROUP 6 ('+REDO01_STOKEN','+REDO02_STOKEN') SIZE 2048M; 
--
--
ALTER SYSTEM SWITCH LOGFILE;
ALTER SYSTEM SWITCH LOGFILE;
ALTER SYSTEM SWITCH LOGFILE;
ALTER SYSTEM CHECKPOINT;
--
--
ALTER DATABASE CLEAR LOGFILE GROUP 1;
ALTER DATABASE DROP LOGFILE GROUP 1;
--
ALTER DATABASE CLEAR LOGFILE GROUP 2;
ALTER DATABASE DROP LOGFILE GROUP 2;
--
ALTER DATABASE CLEAR LOGFILE GROUP 3;
ALTER DATABASE DROP LOGFILE GROUP 3;
--
ALTER DATABASE ADD LOGFILE THREAD 1 GROUP 1 ('+REDO01_STOKEN','+REDO02_STOKEN') SIZE 2048M;
ALTER DATABASE ADD LOGFILE THREAD 1 GROUP 2 ('+REDO01_STOKEN','+REDO02_STOKEN') SIZE 2048M;
ALTER DATABASE ADD LOGFILE THREAD 1 GROUP 3 ('+REDO01_STOKEN','+REDO02_STOKEN') SIZE 2048M; 
--
ALTER SYSTEM SWITCH LOGFILE;
ALTER SYSTEM SWITCH LOGFILE;
ALTER SYSTEM CHECKPOINT;
--
--
ALTER DATABASE CLEAR LOGFILE GROUP 5;
ALTER DATABASE DROP LOGFILE GROUP 5;
--
ALTER DATABASE CLEAR LOGFILE GROUP 6;
ALTER DATABASE DROP LOGFILE GROUP 6;