
SET TIME ON
------------
CREATE TABLE "BDVNET"."BNET_REG_OPER_PIVOT" (  
  "FECHA" DATE NOT NULL ENABLE,
  "CEDULA_CLIENTE" VARCHAR2(20) NOT NULL ENABLE,
  "CEDULA_OTRO" VARCHAR2(20),
  "TXN" VARCHAR2(15) NOT NULL ENABLE,
  "IDRESULTADO" VARCHAR2(12),
  "RESULTADO" VARCHAR2(200) NOT NULL ENABLE,
  "INSTRUMENTO_ORIG" VARCHAR2(20),
  "INSTRUMENTO_DEST" VARCHAR2(20),
  "MONTO" VARCHAR2(30),
  "IP" VARCHAR2(30),
  "SISTEMA_OPERATIVO" VARCHAR2(100),
  "ULTIMA_ACT" DATE DEFAULT SYSDATE NOT NULL ENABLE,
  "ORD_DIA" VARCHAR2(2),
  "ORD_MES" VARCHAR2(2),
  "ORD_ANO" VARCHAR2(4),
  "BENEFICIARIO" VARCHAR2(40),
  "CONCEPTO" VARCHAR2(50),
  "INSTRUMENTO_ORIG1" VARCHAR2(140),
  "INSTRUMENTO_DEST1" VARCHAR2(140),
   CONSTRAINT "BRON_CED_OPER_NEW" PRIMARY KEY ("CEDULA_CLIENTE", "IDRESULTADO", "ORD_MES")
) TABLESPACE "DATA_REG_OPER"
PARTITION BY RANGE (FECHA)
(
  PARTITION P202101 VALUES LESS THAN (TO_DATE('01-FEB-2021', 'DD-MON-YYYY')) TABLESPACE DATA_REG_OPER
)
/
----------------------------------------------------------------------------------------------------
------------
PROMPT TABLA BNET_REG_OPER_PIVOT CREADA
------------
-- CREACION DE LAS PARTICIONES
------------
SET SERVEROUTPUT ON;
DECLARE v_name_partition    VARCHAR2(30);
        v_date_partition    VARCHAR2(30);
        v_tablespace_name   VARCHAR2(50);
        v_ini_date          DATE;
        v_end_date          DATE;
        v_sentence          VARCHAR2(500);

BEGIN
    v_ini_date := TO_DATE('01-02-2021', 'DD-MM-SYYYY');
    v_end_date := TO_DATE('31-12-2025', 'DD-MM-SYYYY');
    v_tablespace_name := 'DATA_REG_OPER';

    WHILE v_ini_date <= v_end_date
    LOOP
        v_name_partition := 'P' || TO_CHAR(v_ini_date, 'YYYYMM');
        v_date_partition := TO_CHAR(ADD_MONTHS(v_ini_date, +1), 'DD-MON-YYYY');

        v_sentence := 'ALTER TABLE "BDVNET"."BNET_REG_OPER_PIVOT" ADD PARTITION ' || v_name_partition 
                        || ' VALUES LESS THAN (TO_DATE(' || CHR(39) || v_date_partition || CHR(39) 
                        || ', ' || CHR(39) 
                        || 'DD-MON-YYYY' || CHR(39) || ')) TABLESPACE ' || v_tablespace_name;

        DBMS_OUTPUT.PUT_LINE(v_sentence);
        EXECUTE IMMEDIATE v_sentence;
        v_ini_date := ADD_MONTHS(v_ini_date, +1);
    END LOOP;
END;
/
------------
PROMPT PARTICION CREADA
------------
set line 200 pagesize 1000
col partition_name for a20
col TABLE_NAME for a30
col high_value for a120
SELECT partition_name
, TABLE_NAME 
, high_value
FROM dba_tab_partitions
WHERE TABLE_OWNER = 'BDVNET'
AND TABLE_NAME = 'BNET_REG_OPER'
ORDER BY PARTITION_POSITION
/
---------------------------
-- DROP DEL CONSTRAINT
---------------------------
SELECT INDEX_NAME FROM DBA_INDEXES WHERE TABLE_NAME='BNET_REG_OPER_ABRIL';
SELECT COUNT (1) FROM BDVNET.BNET_REG_OPER WHERE FECHA = (TO_DATE('01-APR-2024', 'DD-MON-YYYY'))
---------------------------
ALTER TABLE BDVNET.BNET_REG_OPER_ABRIL DROP CONSTRAINT BRO_CED_OPER_N1;
------------
PROMPT CONSTRAINT ELIMINADO
------------
DROP INDEX BDVNET.BRO_CED_OPER_N1
DROP INDEX BDVNET.BRO_CEDFEC_NEW;
DROP INDEX BDVNET.BRO_FECHA_NEW;
DROP INDEX BDVNET.BRO_TXNFEC_NEW;
DROP INDEX BDVNET.BRO_TXN_NEW;
DROP INDEX BDVNET.BRO_TEST_INDEX;
------------
PROMPT INDICES ELIMINADOS
------------
SELECT INDEX_NAME, STATUS FROM DBA_INDEXES WHERE TABLE_NAME='BNET_REG_TRANS';
---------------------------------------------------------------------
--
ALTER INDEX BDVNET.BRO_CED_OPER_N1 MONITORING USAGE;
ALTER INDEX BDVNET.BRO_CEDFEC_NEW  MONITORING USAGE;
ALTER INDEX BDVNET.BRO_FECHA_NEW MONITORING USAGE;
ALTER INDEX BDVNET.BRO_TXNFEC_NEW  MONITORING USAGE;
ALTER INDEX BDVNET.BRO_TXN_NEW  MONITORING USAGE;
ALTER INDEX '||owner||'.'||index_name||' MONITORING USAGE;
--
--
ALTER INDEX BDVNET.BRT_CED_OPER NOPARALLEL;
ALTER INDEX BDVNET.BRO_CEDTXNFECHA NOPARALLEL;
ALTER INDEX BDVNET.BRT_CEDFEC NOPARALLEL;
ALTER INDEX BDVNET.BRT_CEDTXNMES NOPARALLEL;
ALTER INDEX BDVNET.BRT_CLIENTE NOPARALLEL;
ALTER INDEX BDVNET.BRT_FECHA NOPARALLEL;
ALTER INDEX BDVNET.BRT_MES NOPARALLEL;
ALTER INDEX BDVNET.BRT_RESULT_N1 NOPARALLEL;
--------------
set linesize 500
col QUERY format a80
col index_name format a40
col owner format a40
select 'ALTER INDEX '||owner||'.'||index_name||' NOPARALLEL;' QUERY
  ,index_name
  ,owner
  from dba_indexes
where table_name = 'BNET_REG_TRANS';