set pagesize 5000
set linesize 300
col CONSTRAINT_NAME format A50
col owner format a10 
col CONSTRAINT_TYPE format a16
col TABLE_NAME format a50
select OWNER,TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
from (
SELECT OWNER,TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM dba_constraints@TRZSP_SUN 
where owner = 'TX'  and CONSTRAINT_NAME not like 'SYS_%'
minus
SELECT OWNER,TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM dba_constraints
where owner = 'TX'  and CONSTRAINT_NAME not like 'SYS_%'
);


--2518  con los SYS


-- 6 sin los sys
OWNER      TABLE_NAME                                         CONSTRAINT_NAME                                    CONSTRAINT_TYPE
---------- -------------------------------------------------- -------------------------------------------------- ----------------
TX         CARDREADER                                         FK_CARDREADER_TOKENFACTORY                         R
TX         CREDITLINECLITEMDEBTCAT                            PK_CREDITLINECLITEMDEBTCAT                         P
TX         DOEREXTMSG                                         FK_DOEREXTMSG_DOER                                 R
TX         DOEREXTMSG                                         FK_DOEREXTMSG_TRAN                                 R
TX         FINCONTRACTISSUINGCREDITLIMIT                      FK_FINCTRISSCREDITLIMIT                            R
TX         TOKEN                                              FK_TOKEN_CLERK_1                                   R


SELECT DBMS_METADATA.get_ddl ('REF_CONSTRAINT', 'FK_CARDREADER_TOKENFACTORY', 'TX') from dual;

---


  ALTER TABLE "TX"."CREDITLINECLITEMDEBTCAT" ADD CONSTRAINT "PK_CREDITLINECLITEMDEBTCAT" PRIMARY KEY ("DEBTCATID", "CLSCHEMEID") RELY
  USING INDEX "TX"."PK_CREDITLINECLITEMDEBTCAT"  ENABLE;


  ALTER TABLE "TX"."DOEREXTMSG" ADD CONSTRAINT "PK_DOEREXTMSG" PRIMARY KEY ("TRANID", "DOERSEQ") RELY
  USING INDEX "TX"."PK_DOEREXTMSG"  ENABLE;


  ALTER TABLE "TX"."TOKEN" ADD CONSTRAINT "PK_TOKEN" PRIMARY KEY ("ID") RELY
  USING INDEX "TX"."PK_TOKEN"  ENABLE;


  ALTER TABLE "TX"."CARDREADER" ADD CONSTRAINT "PK_CARDREADER" PRIMARY KEY ("ID") RELY
  USING INDEX "TX"."PK_CARDREADER"  ENABLE;

6 rows selected.



SET LONG 200000 LONGCHUNKSIZE 20000 PAGESIZE 0 LINESIZE 10000000 FEEDBACK OFF VERIFY OFF TRIMSPOOL ON
BEGIN
  DBMS_METADATA.set_transform_param (DBMS_METADATA.session_transform, 'SQLTERMINATOR', true);
  DBMS_METADATA.set_transform_param (DBMS_METADATA.session_transform, 'PRETTY', true);
END;
/
spool constraints_faltantes.sql;
select dbms_metadata.get_ddl(CONSTRAINT_NAME, CONSTRAINT_NAME, 'TX')
from dba_constraints@TRZSP_SUN  where CONSTRAINT_NAME in (
'FK_CARDREADER_TOKENFACTORY',
'FK_DOEREXTMSG_DOER',
'FK_DOEREXTMSG_TRAN',
'FK_FINCTRISSCREDITLIMIT',
'FK_TOKEN_CLERK_1',
'PK_CREDITLINECLITEMDEBTCAT'
);
spool off


select dbms_metadata.get_ddl(CONSTRAINT_TYPE, CONSTRAINT_NAME, 'TX')
from dba_constraints@TRZSP_SUN  where CONSTRAINT_NAME in (
'FK_CARDREADER_TOKENFACTORY',
'FK_DOEREXTMSG_DOER',
'FK_DOEREXTMSG_TRAN',
'FK_FINCTRISSCREDITLIMIT',
'FK_TOKEN_CLERK_1',
'PK_CREDITLINECLITEMDEBTCAT'
);

select dbms_metadata.get_ddl('CONSTRAINT', CONSTRAINT_NAME, 'TX')
from dba_constraints  where CONSTRAINT_NAME in (
'FK_CARDREADER_TOKENFACTORY',
'FK_DOEREXTMSG_DOER',
'FK_DOEREXTMSG_TRAN',
'FK_FINCTRISSCREDITLIMIT',
'FK_TOKEN_CLERK_1',
'PK_CREDITLINECLITEMDEBTCAT'
);




/*


 SELECT column_name, constraint_name, table_name
    FROM SYS.DBA_CONS_COLUMNS
   WHERE OWNER = 'TX' AND CONSTRAINT_NAME = 'PK_CREDITLINECLITEMDEBTCAT'
ORDER BY table_name,
         constraint_name,
         position,
         column_name;



         */



SET LONG 20000 LONGCHUNKSIZE 20000 PAGESIZE 0 LINESIZE 1000 FEEDBACK OFF VERIFY OFF TRIMSPOOL ON

BEGIN
   DBMS_METADATA.set_transform_param (DBMS_METADATA.session_transform, 'SQLTERMINATOR', true);
   DBMS_METADATA.set_transform_param (DBMS_METADATA.session_transform, 'PRETTY', true);
END;
/

SELECT DBMS_METADATA.get_ddl ('REF_CONSTRAINT', constraint_name, 'TX')
FROM   dba_constraints
WHERE  owner      = 'TX'
AND    table_name in ('CARDREADER'    
,'DOEREXTMSG'                   
,'DOEREXTMSG'                   
,'FINCONTRACTISSUINGCREDITLIMIT'
,'TOKEN')                        
AND    constraint_type IN ('R');

SET PAGESIZE 14 LINESIZE 100 FEEDBACK ON VERIFY ON



SET LONG 20000 LONGCHUNKSIZE 20000 PAGESIZE 0 LINESIZE 1000 FEEDBACK OFF VERIFY OFF TRIMSPOOL ON

BEGIN
   DBMS_METADATA.set_transform_param (DBMS_METADATA.session_transform, 'SQLTERMINATOR', true);
   DBMS_METADATA.set_transform_param (DBMS_METADATA.session_transform, 'PRETTY', true);
END;
/

SELECT DBMS_METADATA.get_ddl ('REF_CONSTRAINT', constraint_name, 'TX')
FROM   dba_constraints
WHERE  owner      = 'TX'
AND    table_name in ('PK_CREDITLINECLITEMDEBTCAT')                        
AND    constraint_type IN ('U');

SET PAGESIZE 14 LINESIZE 100 FEEDBACK ON VERIFY ON









---




SET LONG 20000 LONGCHUNKSIZE 20000 PAGESIZE 0 LINESIZE 1000 FEEDBACK OFF VERIFY OFF TRIMSPOOL ON

BEGIN
   DBMS_METADATA.set_transform_param (DBMS_METADATA.session_transform, 'SQLTERMINATOR', true);
   DBMS_METADATA.set_transform_param (DBMS_METADATA.session_transform, 'PRETTY', true);
END;
/

select DBMS_METADATA.get_ddl(DECODE(CONSTRAINT_TYPE,'R','REF_CONSTRAINT','CONSTRAINT'), CONSTRAINT_NAME, 'TX')
--OWNER,TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
from (
	SELECT OWNER,TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
	FROM dba_constraints 
	where owner = 'TX'  and CONSTRAINT_NAME not like 'SYS_%'
minus
	SELECT OWNER,TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
	FROM dba_constraints@TRZSP_OL
	where owner = 'TX'  and CONSTRAINT_NAME not like 'SYS_%'
);

SET PAGESIZE 14 LINESIZE 100 FEEDBACK ON VERIFY ON




set pagesize 5000
set linesize 300
select DBMS_METADATA.get_ddl(DECODE(CONSTRAINT_TYPE,'R','REF_CONSTRAINT','CONSTRAINT'), 'FK_CARDREADER_TOKENFACTORY', 'TX') 
FROM dba_constraints
where owner = 'TX' and CONSTRAINT_NAME = 'FK_CARDREADER_TOKENFACTORY';






ALTER TABLE "TX"."CARDREADER" ADD CONSTRAINT "FK_CARDREADER_TOKENFACTORY" FOREIGN KEY ("TOKENFACTORYID")
          REFERENCES "TX"."TOKENFACTORY" ("ID") ON DELETE CASCADE RELY ENABLE NOVALIDATE;



  ALTER TABLE "TX"."CREDITLINECLITEMDEBTCAT" ADD CONSTRAINT "PK_CREDITLINECLITEMDEBTCAT" PRIMARY KEY ("DEBTCATID", "CLSCHEMEID") RELY
  USING INDEX "TX"."PK_CREDITLINECLITEMDEBTCAT"  ENABLE;


  ALTER TABLE "TX"."DOEREXTMSG" ADD CONSTRAINT "FK_DOEREXTMSG_DOER" FOREIGN KEY ("TRANID", "DOERSEQ")
          REFERENCES "TX"."DOER" ("TRANID", "SEQ") RELY DISABLE;


  ALTER TABLE "TX"."DOEREXTMSG" ADD CONSTRAINT "FK_DOEREXTMSG_TRAN" FOREIGN KEY ("TRANID")
          REFERENCES "TX"."TRAN" ("ID") RELY DISABLE;


  ALTER VIEW "TX"."FINCONTRACTISSUINGCREDITLIMIT" ADD CONSTRAINT "FK_FINCTRISSCREDITLIMIT" FOREIGN KEY ("LIMITID")
          REFERENCES "TX"."ISSUINGCREDITLIMIT" ("ID") RELY DISABLE;


  ALTER TABLE "TX"."TOKEN" ADD CONSTRAINT "FK_TOKEN_CLERK_1" FOREIGN KEY ("SECRETSETENABLEDBYCLERK")
          REFERENCES "TX"."RDX_AC_USER" ("NAME") RELY DISABLE;


