spool ddl_index_trzsp_full_5.lst
prompt - ddl_index_trzsp_full_5
set time on timi on

-- CONNECT SYSTEM
ALTER SESSION SET EVENTS '10150 TRACE NAME CONTEXT FOREVER, LEVEL 1';
ALTER SESSION SET EVENTS '10904 TRACE NAME CONTEXT FOREVER, LEVEL 1';
ALTER SESSION SET EVENTS '25475 TRACE NAME CONTEXT FOREVER, LEVEL 1';
ALTER SESSION SET EVENTS '10407 TRACE NAME CONTEXT FOREVER, LEVEL 1';
ALTER SESSION SET EVENTS '10851 TRACE NAME CONTEXT FOREVER, LEVEL 1';
ALTER SESSION SET EVENTS '22830 TRACE NAME CONTEXT FOREVER, LEVEL 192 ';


prompt CREATE INDEX "TX"."IDX_CREDITLINECONTRACT_REPAYSC" ON "TX"."CREDITLINECONTRACT" ("REPAYSCHEMEID") 
CREATE INDEX "TX"."IDX_CREDITLINECONTRACT_REPAYSC" ON "TX"."CREDITLINECONTRACT" ("REPAYSCHEMEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_CREDITLINECONTRACT_REPAYSC" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_TERMSTATE" ON "TX"."TERMSTATE" ("TERMID") 
CREATE UNIQUE INDEX "TX"."PK_TERMSTATE" ON "TX"."TERMSTATE" ("TERMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_TERMSTATE" NOPARALLEL;



prompt CREATE UNIQUE INDEX "TX"."PK_TOKENALIAS" ON "TX"."TOKENALIAS" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_TOKENALIAS" ON "TX"."TOKENALIAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_TOKEN_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_TOKENALIAS" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_TOKENALIAS_TOKENID" ON "TX"."TOKENALIAS" ("TOKENID") 
CREATE INDEX "TX"."IDX_TOKENALIAS_TOKENID" ON "TX"."TOKENALIAS" ("TOKENID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_TOKEN_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_TOKENALIAS_TOKENID" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."IDX_TOKENALIAS_ALIASINNETWORK" ON "TX"."TOKENALIAS" ("NETWORKTYPE", "TOKENID", "TYPE", "VALUE") 
CREATE UNIQUE INDEX "TX"."IDX_TOKENALIAS_ALIASINNETWORK" ON "TX"."TOKENALIAS" ("NETWORKTYPE", "TOKENID", "TYPE", "VALUE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_TOKEN_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_TOKENALIAS_ALIASINNETWORK" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_XDCOPERDECLINERESULT" ON "TX"."XDCOPERDECLINERESULT" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_XDCOPERDECLINERESULT" ON "TX"."XDCOPERDECLINERESULT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_XDCOPERDECLINERESULT" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."IDX_XDCOPERDECLINERESULT_RESUL" ON "TX"."XDCOPERDECLINERESULT" ("ADAPTERID", "OPERID", "DECLINEREASON") 
CREATE UNIQUE INDEX "TX"."IDX_XDCOPERDECLINERESULT_RESUL" ON "TX"."XDCOPERDECLINERESULT" ("ADAPTERID", "OPERID", "DECLINEREASON") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_XDCOPERDECLINERESULT_RESUL" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."IDX_RDX_UNIT_RID" ON "TX"."RDX_UNIT" ("RID") 
CREATE UNIQUE INDEX "TX"."IDX_RDX_UNIT_RID" ON "TX"."RDX_UNIT" ("RID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_RDX_UNIT_RID" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_RDX_UNIT" ON "TX"."RDX_UNIT" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_RDX_UNIT" ON "TX"."RDX_UNIT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."PK_RDX_UNIT" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_TRANPOSTPROCESSORPARAM" ON "TX"."TRANPOSTPROCESSORPARAM" ("ID", "NAME") 
CREATE UNIQUE INDEX "TX"."PK_TRANPOSTPROCESSORPARAM" ON "TX"."TRANPOSTPROCESSORPARAM" ("ID", "NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_TRANPOSTPROCESSORPARAM" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_TRCHRVLCRDDDSCHEME" ON "TX"."TRCHRVLCRDDDSCHEME" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_TRCHRVLCRDDDSCHEME" ON "TX"."TRCHRVLCRDDDSCHEME" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_TRCHRVLCRDDDSCHEME" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_TRCHRVLCRDDDSCHEME_CALENDA" ON "TX"."TRCHRVLCRDDDSCHEME" ("CALENDARID") 
CREATE INDEX "TX"."IDX_TRCHRVLCRDDDSCHEME_CALENDA" ON "TX"."TRCHRVLCRDDDSCHEME" ("CALENDARID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_TRCHRVLCRDDDSCHEME_CALENDA" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_TRCHRVLCRDDDSCHEME_TYPE" ON "TX"."TRCHRVLCRDDDSCHEME" ("CONTRACTTYPEID") 
CREATE INDEX "TX"."IDX_TRCHRVLCRDDDSCHEME_TYPE" ON "TX"."TRCHRVLCRDDDSCHEME" ("CONTRACTTYPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_TRCHRVLCRDDDSCHEME_TYPE" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_TERMBATCHTRAN" ON "TX"."TERMBATCHTRAN" ("TERMID", "BATCHID", "TRANID") 
CREATE UNIQUE INDEX "TX"."PK_TERMBATCHTRAN" ON "TX"."TERMBATCHTRAN" ("TERMID", "BATCHID", "TRANID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_TERMBATCHTRAN" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_RDX_QUEUESAFPARTITION" ON "TX"."RDX_QUEUESAFPARTITION" ("QUEUEID", "ID") 
CREATE UNIQUE INDEX "TX"."PK_RDX_QUEUESAFPARTITION" ON "TX"."RDX_QUEUESAFPARTITION" ("QUEUEID", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."PK_RDX_QUEUESAFPARTITION" NOPARALLEL;




prmpt CREATE UNIQUE INDEX "TX"."PK_RDX_CLASSANCESTOR" ON "TX"."RDX_CLASSANCESTOR" ("VERSIONNUM", "CLASSID", "ANCESTORID") ;
CREATE UNIQUE INDEX "TX"."PK_RDX_CLASSANCESTOR" ON "TX"."RDX_CLASSANCESTOR" ("VERSIONNUM", "CLASSID", "ANCESTORID") ;




prompt CREATE UNIQUE INDEX "TX"."PK_NOTIFYSUBSCRIPTION" ON "TX"."NOTIFYSUBSCRIPTION" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_NOTIFYSUBSCRIPTION" ON "TX"."NOTIFYSUBSCRIPTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_NOTIFYSUBSCRIPTION" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_NOTIFYSUBSCRIPTION_TYPE" ON "TX"."NOTIFYSUBSCRIPTION" ("NOTIFYTYPEID", "ID") 
CREATE INDEX "TX"."IDX_NOTIFYSUBSCRIPTION_TYPE" ON "TX"."NOTIFYSUBSCRIPTION" ("NOTIFYTYPEID", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_NOTIFYSUBSCRIPTION_TYPE" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_NOTIFYSUBSCRIPTION_RID" ON "TX"."NOTIFYSUBSCRIPTION" ("RID", "CONTRACTID") 
CREATE INDEX "TX"."IDX_NOTIFYSUBSCRIPTION_RID" ON "TX"."NOTIFYSUBSCRIPTION" ("RID", "CONTRACTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 166 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_NOTIFYSUBSCRIPTION_RID" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_NOTIFYSUBSCRIPTION_CONTR" ON "TX"."NOTIFYSUBSCRIPTION" ("CONTRACTID") 
CREATE INDEX "TX"."IDX_NOTIFYSUBSCRIPTION_CONTR" ON "TX"."NOTIFYSUBSCRIPTION" ("CONTRACTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_NOTIFYSUBSCRIPTION_CONTR" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_POSTING" ON "TX"."POSTING" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_POSTING" ON "TX"."POSTING" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_POSTING_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_POSTING" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_POSTING_ACCOUNTDAY" ON "TX"."POSTING" ("ACCOUNTID", "OPERDAY", "POSTINGSEQ") 
CREATE INDEX "TX"."IDX_POSTING_ACCOUNTDAY" ON "TX"."POSTING" ("ACCOUNTID", "OPERDAY", "POSTINGSEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_POSTING_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_POSTING_ACCOUNTDAY" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."IDX_CASHFORECASTITEM_TIME" ON "TX"."CASHFORECASTITEM" ("CASHFORECASTID", "TIMEOFFSET") 
CREATE UNIQUE INDEX "TX"."IDX_CASHFORECASTITEM_TIME" ON "TX"."CASHFORECASTITEM" ("CASHFORECASTID", "TIMEOFFSET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_CASHFORECASTITEM_TIME" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_CASHFORECASTITEM" ON "TX"."CASHFORECASTITEM" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_CASHFORECASTITEM" ON "TX"."CASHFORECASTITEM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_CASHFORECASTITEM" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_RDX_TST_AUDITDETAIL" ON "TX"."RDX_TST_AUDITDETAIL" ("PKCOLINT", "PKCOLCHAR", "PKCOLNUM", "PKCOLDATE", "PKCOLSTR", "PKCOLTIMESTAMP") 
CREATE UNIQUE INDEX "TX"."PK_RDX_TST_AUDITDETAIL" ON "TX"."RDX_TST_AUDITDETAIL" ("PKCOLINT", "PKCOLCHAR", "PKCOLNUM", "PKCOLDATE", "PKCOLSTR", "PKCOLTIMESTAMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."PK_RDX_TST_AUDITDETAIL" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_ACCOUNTPLANITEMPARAM" ON "TX"."ACCOUNTPLANITEMPARAM" ("ACCOUNTPLANITEMGUID", "NAME") 
CREATE UNIQUE INDEX "TX"."PK_ACCOUNTPLANITEMPARAM" ON "TX"."ACCOUNTPLANITEMPARAM" ("ACCOUNTPLANITEMGUID", "NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_ACCOUNTPLANITEMPARAM" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_SHARDINGOBJRANGE_NEWSHARD" ON "TX"."SHARDINGOBJRANGE" ("NEWSHARDID") 
CREATE INDEX "TX"."IDX_SHARDINGOBJRANGE_NEWSHARD" ON "TX"."SHARDINGOBJRANGE" ("NEWSHARDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_SHARDINGOBJRANGE_NEWSHARD" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_SHARDINGOBJRANGE_SHARD" ON "TX"."SHARDINGOBJRANGE" ("SHARDID") 
CREATE INDEX "TX"."IDX_SHARDINGOBJRANGE_SHARD" ON "TX"."SHARDINGOBJRANGE" ("SHARDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_SHARDINGOBJRANGE_SHARD" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_SHARDINGOBJRANGE" ON "TX"."SHARDINGOBJRANGE" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_SHARDINGOBJRANGE" ON "TX"."SHARDINGOBJRANGE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_SHARDINGOBJRANGE" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_SHARDINGOBJRANGE_SEQ" ON "TX"."SHARDINGOBJRANGE" ("INSTID", "KIND", "SEQ") 
CREATE INDEX "TX"."IDX_SHARDINGOBJRANGE_SEQ" ON "TX"."SHARDINGOBJRANGE" ("INSTID", "KIND", "SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_SHARDINGOBJRANGE_SEQ" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_RESERVESUBPORTFOLIO" ON "TX"."RESERVESUBPORTFOLIO" ("CONTRACTTYPEID", "SUBPORTFOLIOID") 
CREATE UNIQUE INDEX "TX"."PK_RESERVESUBPORTFOLIO" ON "TX"."RESERVESUBPORTFOLIO" ("CONTRACTTYPEID", "SUBPORTFOLIOID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_RESERVESUBPORTFOLIO" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_UNDONEPOSTING" ON "TX"."UNDONEPOSTING" ("TRANID", "ID") 
CREATE UNIQUE INDEX "TX"."PK_UNDONEPOSTING" ON "TX"."UNDONEPOSTING" ("TRANID", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_POSTING_IDX"  LOCAL
 (PARTITION "UNDONEPOSTING_2024_09_17" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_POSTING_IDX" , 
 PARTITION "UNDONEPOSTING_2024_09_18" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_POSTING_IDX" , 
 PARTITION "UNDONEPOSTING_2024_09_19" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_POSTING_IDX" , 
 PARTITION "UNDONEPOSTING_2024_09_20" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_POSTING_IDX" , 
 PARTITION "UNDONEPOSTING_2024_09_21" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_POSTING_IDX" , 
 PARTITION "UNDONEPOSTING_2024_09_22" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_POSTING_IDX" , 
 PARTITION "UNDONEPOSTING_2024_09_23" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_POSTING_IDX" , 
 PARTITION "UNDONEPOSTING_2024_09_24" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_POSTING_IDX" , 
 PARTITION "UNDONEPOSTING_2024_09_25" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_POSTING_IDX" , 
 PARTITION "UNDONEPOSTING_2024_09_26" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_POSTING_IDX" , 
 PARTITION "UNDONEPOSTING_2024_09_27" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_POSTING_IDX" , 
 PARTITION "UNDONEPOSTING_2024_09_28" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_POSTING_IDX" , 
 PARTITION "UNDONEPOSTING_2024_09_29" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_POSTING_IDX" , 
 PARTITION "UNDONEPOSTING_2024_09_30" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_POSTING_IDX" , 
 PARTITION "UNDONEPOSTING_2024_10_01" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_POSTING_IDX" , 
 PARTITION "UNDONEPOSTING_2024_10_02" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_POSTING_IDX" , 
 PARTITION "UNDONEPOSTING_2024_10_03" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_POSTING_IDX" ) parallel 8
 ;
  ALTER INDEX "TX"."PK_UNDONEPOSTING" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_UDTTYPE_INSTITUTION" ON "TX"."UDTTYPE" ("INSTID") 
CREATE INDEX "TX"."IDX_UDTTYPE_INSTITUTION" ON "TX"."UDTTYPE" ("INSTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_UDTTYPE_INSTITUTION" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_UDTTYPE" ON "TX"."UDTTYPE" ("RID") 
CREATE UNIQUE INDEX "TX"."PK_UDTTYPE" ON "TX"."UDTTYPE" ("RID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_UDTTYPE" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_NS_MC_IP0053T1" ON "TX"."NS_MC_IP0053T1" ("NETWORKSTRUCTUREVERID", "FEECODEPOINTER", "RATETYPE", "PAYMENTPARTY", "SEGMENTNO", "EFFECTIVETIMESTAMP") 
CREATE UNIQUE INDEX "TX"."PK_NS_MC_IP0053T1" ON "TX"."NS_MC_IP0053T1" ("NETWORKSTRUCTUREVERID", "FEECODEPOINTER", "RATETYPE", "PAYMENTPARTY", "SEGMENTNO", "EFFECTIVETIMESTAMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_NS_MC_IP0053T1" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_RDX_EASSESSIONVARS" ON "TX"."RDX_EASSESSIONVARS" ("SESSIONID", "NAME") 
CREATE UNIQUE INDEX "TX"."PK_RDX_EASSESSIONVARS" ON "TX"."RDX_EASSESSIONVARS" ("SESSIONID", "NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."PK_RDX_EASSESSIONVARS" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_IPADDRESSRANGE" ON "TX"."IPADDRESSRANGE" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_IPADDRESSRANGE" ON "TX"."IPADDRESSRANGE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_IPADDRESSRANGE" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_IPADDRESSRANGE_RIR" ON "TX"."IPADDRESSRANGE" ("RIR") 
CREATE INDEX "TX"."IDX_IPADDRESSRANGE_RIR" ON "TX"."IPADDRESSRANGE" ("RIR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_IPADDRESSRANGE_RIR" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_IPADDRESSRANGE_COUNTRY" ON "TX"."IPADDRESSRANGE" ("COUNTRYID") 
CREATE INDEX "TX"."IDX_IPADDRESSRANGE_COUNTRY" ON "TX"."IPADDRESSRANGE" ("COUNTRYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_IPADDRESSRANGE_COUNTRY" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_IPADDRESSRANGE_LOWBOUND" ON "TX"."IPADDRESSRANGE" ("LOWBOUND") 
CREATE INDEX "TX"."IDX_IPADDRESSRANGE_LOWBOUND" ON "TX"."IPADDRESSRANGE" ("LOWBOUND") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_IPADDRESSRANGE_LOWBOUND" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_RESERVEQUALCATEGORYOLD" ON "TX"."RESERVEQUALCATEGORYOLD" ("CONTRACTTYPEID", "FINANCIALCATEGORY", "DEBTCATEGORY") 
CREATE UNIQUE INDEX "TX"."PK_RESERVEQUALCATEGORYOLD" ON "TX"."RESERVEQUALCATEGORYOLD" ("CONTRACTTYPEID", "FINANCIALCATEGORY", "DEBTCATEGORY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_RESERVEQUALCATEGORYOLD" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_RDX_CM_SNAPSHOTREC" ON "TX"."RDX_CM_SNAPSHOTREC" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_RDX_CM_SNAPSHOTREC" ON "TX"."RDX_CM_SNAPSHOTREC" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."PK_RDX_CM_SNAPSHOTREC" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."IDX_RDX_CM_SNAPSHOTREC_SNAPREC" ON "TX"."RDX_CM_SNAPSHOTREC" ("TABLEID", "PID") 
CREATE UNIQUE INDEX "TX"."IDX_RDX_CM_SNAPSHOTREC_SNAPREC" ON "TX"."RDX_CM_SNAPSHOTREC" ("TABLEID", "PID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 166 
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_RDX_CM_SNAPSHOTREC_SNAPREC" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_RDX_MQPROCESSOROFFSET" ON "TX"."RDX_MQPROCESSOROFFSET" ("PROCESSORID", "PARTITIONID") 
CREATE UNIQUE INDEX "TX"."PK_RDX_MQPROCESSOROFFSET" ON "TX"."RDX_MQPROCESSOROFFSET" ("PROCESSORID", "PARTITIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."PK_RDX_MQPROCESSOROFFSET" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_BRANCH_SURCHTARIFFPLAN" ON "TX"."BRANCH" ("SURCHARGETARIFFPLANGUID") 
CREATE INDEX "TX"."IDX_BRANCH_SURCHTARIFFPLAN" ON "TX"."BRANCH" ("SURCHARGETARIFFPLANGUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_BRANCH_SURCHTARIFFPLAN" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_BRANCH_DEPARTMENT" ON "TX"."BRANCH" ("DEPARTMENTID") 
CREATE INDEX "TX"."IDX_BRANCH_DEPARTMENT" ON "TX"."BRANCH" ("DEPARTMENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_BRANCH_DEPARTMENT" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_BRANCH" ON "TX"."BRANCH" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_BRANCH" ON "TX"."BRANCH" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_BRANCH" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."IDX_BRANCH_NAME" ON "TX"."BRANCH" ("INSTID", "NAME") 
CREATE UNIQUE INDEX "TX"."IDX_BRANCH_NAME" ON "TX"."BRANCH" ("INSTID", "NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_BRANCH_NAME" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_BRANCH_PARENTBRANCHID" ON "TX"."BRANCH" ("PARENTBRANCHID", "NAME") 
CREATE INDEX "TX"."IDX_BRANCH_PARENTBRANCHID" ON "TX"."BRANCH" ("PARENTBRANCHID", "NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_BRANCH_PARENTBRANCHID" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_RDX_MT_DEF2DOMAIN" ON "TX"."RDX_MT_DEF2DOMAIN" ("REVISIONMETAID", "DEFID", "DOMAINID") 
CREATE UNIQUE INDEX "TX"."PK_RDX_MT_DEF2DOMAIN" ON "TX"."RDX_MT_DEF2DOMAIN" ("REVISIONMETAID", "DEFID", "DOMAINID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."PK_RDX_MT_DEF2DOMAIN" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_TRCHRVLCRDENTRYCATITEM_DEB" ON "TX"."TRCHRVLCRDENTRYCATITEM" ("DEBTCATID") 
CREATE INDEX "TX"."IDX_TRCHRVLCRDENTRYCATITEM_DEB" ON "TX"."TRCHRVLCRDENTRYCATITEM" ("DEBTCATID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_TRCHRVLCRDENTRYCATITEM_DEB" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_TRCHRVLCRDENTRYCATITEM" ON "TX"."TRCHRVLCRDENTRYCATITEM" ("SCHEMEID", "DEBTCATID") 
CREATE UNIQUE INDEX "TX"."PK_TRCHRVLCRDENTRYCATITEM" ON "TX"."TRCHRVLCRDENTRYCATITEM" ("SCHEMEID", "DEBTCATID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_TRCHRVLCRDENTRYCATITEM" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_CONTRACTSTRATEGYTYPE" ON "TX"."CONTRACTSTRATEGYTYPE" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_CONTRACTSTRATEGYTYPE" ON "TX"."CONTRACTSTRATEGYTYPE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_CONTRACTSTRATEGYTYPE" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_CONTRACTSTRATEGYTYPE_RID" ON "TX"."CONTRACTSTRATEGYTYPE" ("INSTID", "RID") 
CREATE INDEX "TX"."IDX_CONTRACTSTRATEGYTYPE_RID" ON "TX"."CONTRACTSTRATEGYTYPE" ("INSTID", "RID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_CONTRACTSTRATEGYTYPE_RID" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_CONTRACTSTRATEGYTYPE_PAREN" ON "TX"."CONTRACTSTRATEGYTYPE" ("PARENTID") 
CREATE INDEX "TX"."IDX_CONTRACTSTRATEGYTYPE_PAREN" ON "TX"."CONTRACTSTRATEGYTYPE" ("PARENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_CONTRACTSTRATEGYTYPE_PAREN" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_NETWORKSTRUCTUREVER" ON "TX"."NETWORKSTRUCTUREVER" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_NETWORKSTRUCTUREVER" ON "TX"."NETWORKSTRUCTUREVER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_NETWORKSTRUCTUREVER" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."IDX_NETWORKSTRUCTUREVER_UNIQUE" ON "TX"."NETWORKSTRUCTUREVER" ("NETWORKSTRUCTUREID", "RELEASEVERSION") 
CREATE UNIQUE INDEX "TX"."IDX_NETWORKSTRUCTUREVER_UNIQUE" ON "TX"."NETWORKSTRUCTUREVER" ("NETWORKSTRUCTUREID", "RELEASEVERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_NETWORKSTRUCTUREVER_UNIQUE" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_LOANPAYMENTSCHEDULEGENERATO" ON "TX"."LOANPAYMENTSCHEDULEGENERATOR" ("GUID") 
CREATE UNIQUE INDEX "TX"."PK_LOANPAYMENTSCHEDULEGENERATO" ON "TX"."LOANPAYMENTSCHEDULEGENERATOR" ("GUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_LOANPAYMENTSCHEDULEGENERATO" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_NS_MC_IP0093T1" ON "TX"."NS_MC_IP0093T1" ("NETWORKSTRUCTUREVERID", "MINRANGE", "BSATYPE", "BSAID", "EFFECTIVETIMESTAMP") 
CREATE UNIQUE INDEX "TX"."PK_NS_MC_IP0093T1" ON "TX"."NS_MC_IP0093T1" ("NETWORKSTRUCTUREVERID", "MINRANGE", "BSATYPE", "BSAID", "EFFECTIVETIMESTAMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_NS_MC_IP0093T1" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_FEEACCOUNTINGRULE_STI" ON "TX"."FEEACCOUNTINGRULE" ("STRATEGYTYPEID") 
CREATE INDEX "TX"."IDX_FEEACCOUNTINGRULE_STI" ON "TX"."FEEACCOUNTINGRULE" ("STRATEGYTYPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_FEEACCOUNTINGRULE_STI" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_FEEACCOUNTINGRULE_BASERULE" ON "TX"."FEEACCOUNTINGRULE" ("BASERULEID") 
CREATE INDEX "TX"."IDX_FEEACCOUNTINGRULE_BASERULE" ON "TX"."FEEACCOUNTINGRULE" ("BASERULEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_FEEACCOUNTINGRULE_BASERULE" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_FEEACCOUNTINGRULE" ON "TX"."FEEACCOUNTINGRULE" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_FEEACCOUNTINGRULE" ON "TX"."FEEACCOUNTINGRULE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_FEEACCOUNTINGRULE" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_FEEACCOUNTINGRULE_DEBTCATI" ON "TX"."FEEACCOUNTINGRULE" ("DEBTCATEGORYID") 
CREATE INDEX "TX"."IDX_FEEACCOUNTINGRULE_DEBTCATI" ON "TX"."FEEACCOUNTINGRULE" ("DEBTCATEGORYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_FEEACCOUNTINGRULE_DEBTCATI" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_FEEACCOUNTINGRULE_ECC" ON "TX"."FEEACCOUNTINGRULE" ("ENTRYCATEGORYCODE") 
CREATE INDEX "TX"."IDX_FEEACCOUNTINGRULE_ECC" ON "TX"."FEEACCOUNTINGRULE" ("ENTRYCATEGORYCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_FEEACCOUNTINGRULE_ECC" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_TOKENPACKAGE" ON "TX"."TOKENPACKAGE" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_TOKENPACKAGE" ON "TX"."TOKENPACKAGE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_TOKENPACKAGE" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_TOKENPACKAGE_RID" ON "TX"."TOKENPACKAGE" ("INSTID", "RID") 
CREATE INDEX "TX"."IDX_TOKENPACKAGE_RID" ON "TX"."TOKENPACKAGE" ("INSTID", "RID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_TOKENPACKAGE_RID" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_TOKENPACKAGE_FROMPACKAGE" ON "TX"."TOKENPACKAGE" ("TRANSFORMEDFROMPACKAGEID", "ID") 
CREATE INDEX "TX"."IDX_TOKENPACKAGE_FROMPACKAGE" ON "TX"."TOKENPACKAGE" ("TRANSFORMEDFROMPACKAGEID", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_TOKENPACKAGE_FROMPACKAGE" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_TOKENPACKAGE_TOPACKAGE" ON "TX"."TOKENPACKAGE" ("TRANSFORMEDTOPACKAGEID", "ID") 
CREATE INDEX "TX"."IDX_TOKENPACKAGE_TOPACKAGE" ON "TX"."TOKENPACKAGE" ("TRANSFORMEDTOPACKAGEID", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_TOKENPACKAGE_TOPACKAGE" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_TOKENPACKAGE_TERMINAL" ON "TX"."TOKENPACKAGE" ("TERMINALID", "ID") 
CREATE INDEX "TX"."IDX_TOKENPACKAGE_TERMINAL" ON "TX"."TOKENPACKAGE" ("TERMINALID", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_TOKENPACKAGE_TERMINAL" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_TOKENPACKAGE_CONTRACT" ON "TX"."TOKENPACKAGE" ("CONTRACTID", "ID") 
CREATE INDEX "TX"."IDX_TOKENPACKAGE_CONTRACT" ON "TX"."TOKENPACKAGE" ("CONTRACTID", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_TOKENPACKAGE_CONTRACT" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_APPLICATIONTYPEDIR" ON "TX"."APPLICATIONTYPEDIR" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_APPLICATIONTYPEDIR" ON "TX"."APPLICATIONTYPEDIR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_APPLICATIONTYPEDIR" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_NS_MC_IP0035T1" ON "TX"."NS_MC_IP0035T1" ("NETWORKSTRUCTUREVERID", "CRITERIAID", "ACQUIRINGBIN", "INPUTSOURCEID", "EFFECTIVETIMESTAMP") 
CREATE UNIQUE INDEX "TX"."PK_NS_MC_IP0035T1" ON "TX"."NS_MC_IP0035T1" ("NETWORKSTRUCTUREVERID", "CRITERIAID", "ACQUIRINGBIN", "INPUTSOURCEID", "EFFECTIVETIMESTAMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_NS_MC_IP0035T1" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_TRCHRVLCRDCONTRACT" ON "TX"."TRCHRVLCRDCONTRACT" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_TRCHRVLCRDCONTRACT" ON "TX"."TRCHRVLCRDCONTRACT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_TRCHRVLCRDCONTRACT" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_RATEGROUP" ON "TX"."RATEGROUP" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_RATEGROUP" ON "TX"."RATEGROUP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_RATEGROUP" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_RATEGROUP_CROSSCCY" ON "TX"."RATEGROUP" ("CROSSCCY") 
CREATE INDEX "TX"."IDX_RATEGROUP_CROSSCCY" ON "TX"."RATEGROUP" ("CROSSCCY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_RATEGROUP_CROSSCCY" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."IDX_RATEGROUP_NAME" ON "TX"."RATEGROUP" ("INSTID", "BRANCHID", "NAME") 
CREATE UNIQUE INDEX "TX"."IDX_RATEGROUP_NAME" ON "TX"."RATEGROUP" ("INSTID", "BRANCHID", "NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_RATEGROUP_NAME" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_ACCOUNT" ON "TX"."ACCOUNT" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_ACCOUNT" ON "TX"."ACCOUNT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_ACCOUNT" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."IDX_ACCOUNT_NUMBER" ON "TX"."ACCOUNT" ("INSTID", "NUMBER_") 
CREATE UNIQUE INDEX "TX"."IDX_ACCOUNT_NUMBER" ON "TX"."ACCOUNT" ("INSTID", "NUMBER_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_ACCOUNT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_ACCOUNT_NUMBER" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_ACCOUNT_TERMINAL" ON "TX"."ACCOUNT" ("TERMINALID") 
CREATE INDEX "TX"."IDX_ACCOUNT_TERMINAL" ON "TX"."ACCOUNT" ("TERMINALID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_ACCOUNT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_ACCOUNT_TERMINAL" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_ACCOUNT_HASH" ON "TX"."ACCOUNT" ("INSTID", "MAINTAINBALANCEHIST", "HASH") 
CREATE INDEX "TX"."IDX_ACCOUNT_HASH" ON "TX"."ACCOUNT" ("INSTID", "MAINTAINBALANCEHIST", "HASH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_ACCOUNT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_ACCOUNT_HASH" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_ACCOUNT_PLANITEM" ON "TX"."ACCOUNT" ("PLANITEMGUID", "INSTID", "NUMBER_") 
CREATE INDEX "TX"."IDX_ACCOUNT_PLANITEM" ON "TX"."ACCOUNT" ("PLANITEMGUID", "INSTID", "NUMBER_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_ACCOUNT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_ACCOUNT_PLANITEM" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_ACCOUNT_EXTNUMBER" ON "TX"."ACCOUNT" ("EXTNUMBER", "INSTID") 
CREATE INDEX "TX"."IDX_ACCOUNT_EXTNUMBER" ON "TX"."ACCOUNT" ("EXTNUMBER", "INSTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_ACCOUNT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_ACCOUNT_EXTNUMBER" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_ACCOUNT_CONTRACT" ON "TX"."ACCOUNT" ("CONTRACTID") 
CREATE INDEX "TX"."IDX_ACCOUNT_CONTRACT" ON "TX"."ACCOUNT" ("CONTRACTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_ACCOUNT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_ACCOUNT_CONTRACT" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_RDX_UPVALDATETIME" ON "TX"."RDX_UPVALDATETIME" ("DEFID", "OWNERENTITYID", "OWNERPID") 
CREATE UNIQUE INDEX "TX"."PK_RDX_UPVALDATETIME" ON "TX"."RDX_UPVALDATETIME" ("DEFID", "OWNERENTITYID", "OWNERPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."PK_RDX_UPVALDATETIME" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_RDX_UPVALDATETIME_OWNER" ON "TX"."RDX_UPVALDATETIME" ("OWNERENTITYID", "OWNERPID") 
CREATE INDEX "TX"."IDX_RDX_UPVALDATETIME_OWNER" ON "TX"."RDX_UPVALDATETIME" ("OWNERENTITYID", "OWNERPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_RDX_UPVALDATETIME_OWNER" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_INVOICE_GUID" ON "TX"."INVOICE" ("GUID") 
CREATE INDEX "TX"."IDX_INVOICE_GUID" ON "TX"."INVOICE" ("GUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_INVOICE_GUID" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_INVOICE_SUBSCRIPTION" ON "TX"."INVOICE" ("SUBSCRIPTIONCONTRACTID") 
CREATE INDEX "TX"."IDX_INVOICE_SUBSCRIPTION" ON "TX"."INVOICE" ("SUBSCRIPTIONCONTRACTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_INVOICE_SUBSCRIPTION" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_INVOICE_RIDBYPAYER" ON "TX"."INVOICE" ("RIDBYPAYER") 
CREATE INDEX "TX"."IDX_INVOICE_RIDBYPAYER" ON "TX"."INVOICE" ("RIDBYPAYER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_INVOICE_RIDBYPAYER" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_INVOICE" ON "TX"."INVOICE" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_INVOICE" ON "TX"."INVOICE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_INVOICE" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_INVOICE_TYPE" ON "TX"."INVOICE" ("TYPEID", "ID") 
CREATE INDEX "TX"."IDX_INVOICE_TYPE" ON "TX"."INVOICE" ("TYPEID", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_INVOICE_TYPE" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_INVOICE_ACTIONTIME" ON "TX"."INVOICE" ("ACTIONTIME", "STATUS") 
CREATE INDEX "TX"."IDX_INVOICE_ACTIONTIME" ON "TX"."INVOICE" ("ACTIONTIME", "STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_INVOICE_ACTIONTIME" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_INVOICE_DISPUTERIDBYTRX" ON "TX"."INVOICE" ("DISPUTERIDBYTRX") 
CREATE INDEX "TX"."IDX_INVOICE_DISPUTERIDBYTRX" ON "TX"."INVOICE" ("DISPUTERIDBYTRX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_INVOICE_DISPUTERIDBYTRX" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_INVOICE_SRCEXTCARD" ON "TX"."INVOICE" ("SRCEXTCARDID") 
CREATE INDEX "TX"."IDX_INVOICE_SRCEXTCARD" ON "TX"."INVOICE" ("SRCEXTCARDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_INVOICE_SRCEXTCARD" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_INVOICE_RIDBYTRX" ON "TX"."INVOICE" ("RIDBYTRX") 
CREATE INDEX "TX"."IDX_INVOICE_RIDBYTRX" ON "TX"."INVOICE" ("RIDBYTRX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_INVOICE_RIDBYTRX" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_INVOICE_DSTCONTRACT" ON "TX"."INVOICE" ("DSTCONTRACTID") 
CREATE INDEX "TX"."IDX_INVOICE_DSTCONTRACT" ON "TX"."INVOICE" ("DSTCONTRACTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_INVOICE_DSTCONTRACT" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_INVOICE_TEMPLATEOWNER" ON "TX"."INVOICE" ("TEMPLATEOWNERID") 
CREATE INDEX "TX"."IDX_INVOICE_TEMPLATEOWNER" ON "TX"."INVOICE" ("TEMPLATEOWNERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_INVOICE_TEMPLATEOWNER" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_INVOICE_SRCCONTRACT" ON "TX"."INVOICE" ("SRCCONTRACTID") 
CREATE INDEX "TX"."IDX_INVOICE_SRCCONTRACT" ON "TX"."INVOICE" ("SRCCONTRACTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_INVOICE_SRCCONTRACT" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_INVOICE_RIDBYPAYEE" ON "TX"."INVOICE" ("RIDBYPAYEE") 
CREATE INDEX "TX"."IDX_INVOICE_RIDBYPAYEE" ON "TX"."INVOICE" ("RIDBYPAYEE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_INVOICE_RIDBYPAYEE" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_INVOICE_INST" ON "TX"."INVOICE" ("INSTID") 
CREATE INDEX "TX"."IDX_INVOICE_INST" ON "TX"."INVOICE" ("INSTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_INVOICE_INST" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_INVOICE_STATUSTIME" ON "TX"."INVOICE" ("STATUSTIME", "STATUS") 
CREATE INDEX "TX"."IDX_INVOICE_STATUSTIME" ON "TX"."INVOICE" ("STATUSTIME", "STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_INVOICE_STATUSTIME" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_INVOICE_CALLBACKINTERFACE" ON "TX"."INVOICE" ("CALLBACKINTERFACEID") 
CREATE INDEX "TX"."IDX_INVOICE_CALLBACKINTERFACE" ON "TX"."INVOICE" ("CALLBACKINTERFACEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_INVOICE_CALLBACKINTERFACE" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_INVOICE_DSTEXTCARD" ON "TX"."INVOICE" ("DSTEXTCARDID") 
CREATE INDEX "TX"."IDX_INVOICE_DSTEXTCARD" ON "TX"."INVOICE" ("DSTEXTCARDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_INVOICE_DSTEXTCARD" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_INVOICE_EXPTIME" ON "TX"."INVOICE" ("EXPTIME") 
CREATE INDEX "TX"."IDX_INVOICE_EXPTIME" ON "TX"."INVOICE" ("EXPTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_INVOICE_EXPTIME" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_RDX_TST_TEDCPARENT" ON "TX"."RDX_TST_TEDCPARENT" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_RDX_TST_TEDCPARENT" ON "TX"."RDX_TST_TEDCPARENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."PK_RDX_TST_TEDCPARENT" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_RDX_UPVALREF_OWNER" ON "TX"."RDX_UPVALREF" ("OWNERENTITYID", "OWNERPID") 
CREATE INDEX "TX"."IDX_RDX_UPVALREF_OWNER" ON "TX"."RDX_UPVALREF" ("OWNERENTITYID", "OWNERPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_RDX_UPVALREF_OWNER" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_RDX_UPVALREF" ON "TX"."RDX_UPVALREF" ("DEFID", "OWNERENTITYID", "OWNERPID") 
CREATE UNIQUE INDEX "TX"."PK_RDX_UPVALREF" ON "TX"."RDX_UPVALREF" ("DEFID", "OWNERENTITYID", "OWNERPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."PK_RDX_UPVALREF" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_USERGROUP2ROLE_BRANCH" ON "TX"."RDX_AC_USERGROUP2ROLE" ("PA$$5ZOQHCO35XORDCV2AANE2UAFXA") 
CREATE INDEX "TX"."IDX_USERGROUP2ROLE_BRANCH" ON "TX"."RDX_AC_USERGROUP2ROLE" ("PA$$5ZOQHCO35XORDCV2AANE2UAFXA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_USERGROUP2ROLE_BRANCH" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_RDX_AC_USERGROUP2ROLE_USER" ON "TX"."RDX_AC_USERGROUP2ROLE" ("PA$$1ZOQHCO35XORDCV2AANE2UAFXA") 
CREATE INDEX "TX"."IDX_RDX_AC_USERGROUP2ROLE_USER" ON "TX"."RDX_AC_USERGROUP2ROLE" ("PA$$1ZOQHCO35XORDCV2AANE2UAFXA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_RDX_AC_USERGROUP2ROLE_USER" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_RDX_AC_USERGROUP2ROLE_ROLE" ON "TX"."RDX_AC_USERGROUP2ROLE" ("ROLEID") 
CREATE INDEX "TX"."IDX_RDX_AC_USERGROUP2ROLE_ROLE" ON "TX"."RDX_AC_USERGROUP2ROLE" ("ROLEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_RDX_AC_USERGROUP2ROLE_ROLE" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_USERGROUP2ROLE_TOKENPRODUC" ON "TX"."RDX_AC_USERGROUP2ROLE" ("PA$$ZSW4L5OTSBHZFKKEMXRWJ43XPE") 
CREATE INDEX "TX"."IDX_USERGROUP2ROLE_TOKENPRODUC" ON "TX"."RDX_AC_USERGROUP2ROLE" ("PA$$ZSW4L5OTSBHZFKKEMXRWJ43XPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_USERGROUP2ROLE_TOKENPRODUC" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_USERGROUP2ROLE_MONFOLDER" ON "TX"."RDX_AC_USERGROUP2ROLE" ("PA$$LEYTONB7VFDOLMYXO3NTM3UJ6Y") 
CREATE INDEX "TX"."IDX_USERGROUP2ROLE_MONFOLDER" ON "TX"."RDX_AC_USERGROUP2ROLE" ("PA$$LEYTONB7VFDOLMYXO3NTM3UJ6Y") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_USERGROUP2ROLE_MONFOLDER" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_RDX_AC_USERGROUP2ROLE_DASH" ON "TX"."RDX_AC_USERGROUP2ROLE" ("PA$$4PQ4U65VK5HFVJ32XCUORBKRJM") 
CREATE INDEX "TX"."IDX_RDX_AC_USERGROUP2ROLE_DASH" ON "TX"."RDX_AC_USERGROUP2ROLE" ("PA$$4PQ4U65VK5HFVJ32XCUORBKRJM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_RDX_AC_USERGROUP2ROLE_DASH" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_RDX_AC_USERGROUP2ROLE_GROU" ON "TX"."RDX_AC_USERGROUP2ROLE" ("GROUPNAME") 
CREATE INDEX "TX"."IDX_RDX_AC_USERGROUP2ROLE_GROU" ON "TX"."RDX_AC_USERGROUP2ROLE" ("GROUPNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_RDX_AC_USERGROUP2ROLE_GROU" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."IDX_RDX_AC_USERGROUP2ROLE_REPL" ON "TX"."RDX_AC_USERGROUP2ROLE" ("REPLACEDID") 
CREATE UNIQUE INDEX "TX"."IDX_RDX_AC_USERGROUP2ROLE_REPL" ON "TX"."RDX_AC_USERGROUP2ROLE" ("REPLACEDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_RDX_AC_USERGROUP2ROLE_REPL" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_USERGROUP2ROLE_SUBJECTTYPE" ON "TX"."RDX_AC_USERGROUP2ROLE" ("PA$$RKHGC72LZZBYTCLELCC6CP3SUQ") 
CREATE INDEX "TX"."IDX_USERGROUP2ROLE_SUBJECTTYPE" ON "TX"."RDX_AC_USERGROUP2ROLE" ("PA$$RKHGC72LZZBYTCLELCC6CP3SUQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_USERGROUP2ROLE_SUBJECTTYPE" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_RDX_AC_USERGROUP2ROLE" ON "TX"."RDX_AC_USERGROUP2ROLE" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_RDX_AC_USERGROUP2ROLE" ON "TX"."RDX_AC_USERGROUP2ROLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."PK_RDX_AC_USERGROUP2ROLE" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_USERGROUP2ROLE_INSTITUTION" ON "TX"."RDX_AC_USERGROUP2ROLE" ("PA$$4ZOQHCO35XORDCV2AANE2UAFXA") 
CREATE INDEX "TX"."IDX_USERGROUP2ROLE_INSTITUTION" ON "TX"."RDX_AC_USERGROUP2ROLE" ("PA$$4ZOQHCO35XORDCV2AANE2UAFXA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_USERGROUP2ROLE_INSTITUTION" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_USERGROUP2ROLE_ISSUETYPEIN" ON "TX"."RDX_AC_USERGROUP2ROLE" ("PA$$2SWTHWY375GZZN2G35AT7KFLX4") 
CREATE INDEX "TX"."IDX_USERGROUP2ROLE_ISSUETYPEIN" ON "TX"."RDX_AC_USERGROUP2ROLE" ("PA$$2SWTHWY375GZZN2G35AT7KFLX4") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_USERGROUP2ROLE_ISSUETYPEIN" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_CONTRACTTYPETEMPLATE_BASET" ON "TX"."CONTRACTTYPETEMPLATE" ("BASETYPEID") 
CREATE INDEX "TX"."IDX_CONTRACTTYPETEMPLATE_BASET" ON "TX"."CONTRACTTYPETEMPLATE" ("BASETYPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_CONTRACTTYPETEMPLATE_BASET" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_CONTRACTTYPETEMPLATE" ON "TX"."CONTRACTTYPETEMPLATE" ("CONTRACTTYPEID", "ROLE") 
CREATE UNIQUE INDEX "TX"."PK_CONTRACTTYPETEMPLATE" ON "TX"."CONTRACTTYPETEMPLATE" ("CONTRACTTYPEID", "ROLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 166 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_CONTRACTTYPETEMPLATE" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_CONTRACTTYPETEMPLATE_OVRTA" ON "TX"."CONTRACTTYPETEMPLATE" ("OVRTARIFFPLANID") 
CREATE INDEX "TX"."IDX_CONTRACTTYPETEMPLATE_OVRTA" ON "TX"."CONTRACTTYPETEMPLATE" ("OVRTARIFFPLANID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_CONTRACTTYPETEMPLATE_OVRTA" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_RDX_ST_STATCELL_DIMENSIONS" ON "TX"."RDX_ST_STATCELL" ("BLOCKID", "DIMENSION0", "DIMENSION1") 
CREATE INDEX "TX"."IDX_RDX_ST_STATCELL_DIMENSIONS" ON "TX"."RDX_ST_STATCELL" ("BLOCKID", "DIMENSION0", "DIMENSION1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_RDX_ST_STATCELL_DIMENSIONS" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_RDX_ST_STATCELL" ON "TX"."RDX_ST_STATCELL" ("BLOCKID", "BEGTIME", "ENDTIME", "CELLID") 
CREATE UNIQUE INDEX "TX"."PK_RDX_ST_STATCELL" ON "TX"."RDX_ST_STATCELL" ("BLOCKID", "BEGTIME", "ENDTIME", "CELLID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."PK_RDX_ST_STATCELL" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_APPLICATIONPHASE_RID" ON "TX"."APPLICATIONPHASE" ("RID") 
CREATE INDEX "TX"."IDX_APPLICATIONPHASE_RID" ON "TX"."APPLICATIONPHASE" ("RID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_APPLICATIONPHASE_RID" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_APPLICATIONPHASE" ON "TX"."APPLICATIONPHASE" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_APPLICATIONPHASE" ON "TX"."APPLICATIONPHASE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_APPLICATIONPHASE" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_TERMERRORPROCESSDEVICE" ON "TX"."TERMERRORPROCESSDEVICE" ("PROFILEID", "DEVICE") 
CREATE UNIQUE INDEX "TX"."PK_TERMERRORPROCESSDEVICE" ON "TX"."TERMERRORPROCESSDEVICE" ("PROFILEID", "DEVICE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_TERMERRORPROCESSDEVICE" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_DIGITIZATIONSERVICE" ON "TX"."DIGITIZATIONSERVICE" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_DIGITIZATIONSERVICE" ON "TX"."DIGITIZATIONSERVICE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_DIGITIZATIONSERVICE" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."IDX_DIGITIZATIONSERVICE_RID" ON "TX"."DIGITIZATIONSERVICE" ("RID") 
CREATE UNIQUE INDEX "TX"."IDX_DIGITIZATIONSERVICE_RID" ON "TX"."DIGITIZATIONSERVICE" ("RID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_DIGITIZATIONSERVICE_RID" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_XDCOPERATION_CONTRACT" ON "TX"."XDCOPERATION" ("PAYEECONTRACTID") 
CREATE INDEX "TX"."IDX_XDCOPERATION_CONTRACT" ON "TX"."XDCOPERATION" ("PAYEECONTRACTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_XDCOPERATION_CONTRACT" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_XDCOPERATION_ADAPTER" ON "TX"."XDCOPERATION" ("ADAPTERID") 
CREATE INDEX "TX"."IDX_XDCOPERATION_ADAPTER" ON "TX"."XDCOPERATION" ("ADAPTERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_XDCOPERATION_ADAPTER" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_XDCOPERATION" ON "TX"."XDCOPERATION" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_XDCOPERATION" ON "TX"."XDCOPERATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_XDCOPERATION" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_RDX_SB_TRANSFORMSTAGE" ON "TX"."RDX_SB_TRANSFORMSTAGE" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_RDX_SB_TRANSFORMSTAGE" ON "TX"."RDX_SB_TRANSFORMSTAGE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."PK_RDX_SB_TRANSFORMSTAGE" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."IDX_COUNTRY_CODE3" ON "TX"."COUNTRY" ("ALPHA3CODE") 
CREATE UNIQUE INDEX "TX"."IDX_COUNTRY_CODE3" ON "TX"."COUNTRY" ("ALPHA3CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_COUNTRY_CODE3" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."IDX_COUNTRY_CODE2" ON "TX"."COUNTRY" ("ALPHA2CODE") 
CREATE UNIQUE INDEX "TX"."IDX_COUNTRY_CODE2" ON "TX"."COUNTRY" ("ALPHA2CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_COUNTRY_CODE2" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_COUNTRY" ON "TX"."COUNTRY" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_COUNTRY" ON "TX"."COUNTRY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_COUNTRY" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_TRCHRVLCRDDEBTCAT_CONTRACT" ON "TX"."TRCHRVLCRDDEBTCAT" ("CONTRACTTYPEID") 
CREATE INDEX "TX"."IDX_TRCHRVLCRDDEBTCAT_CONTRACT" ON "TX"."TRCHRVLCRDDEBTCAT" ("CONTRACTTYPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_TRCHRVLCRDDEBTCAT_CONTRACT" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_TRCHRVLCRDDEBTCAT" ON "TX"."TRCHRVLCRDDEBTCAT" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_TRCHRVLCRDDEBTCAT" ON "TX"."TRCHRVLCRDDEBTCAT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_TRCHRVLCRDDEBTCAT" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_SETTLEMENTPAYMENTMV_SETTLE" ON "TX"."SETTLEMENTPAYMENTMV" ("SETTLEDAY", "ACCTID") 
CREATE INDEX "TX"."IDX_SETTLEMENTPAYMENTMV_SETTLE" ON "TX"."SETTLEMENTPAYMENTMV" ("SETTLEDAY", "ACCTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_SETTLEMENTPAYMENTMV_SETTLE" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_SETTLEMENTPAYMENTMV" ON "TX"."SETTLEMENTPAYMENTMV" ("ACCTID") 
CREATE UNIQUE INDEX "TX"."PK_SETTLEMENTPAYMENTMV" ON "TX"."SETTLEMENTPAYMENTMV" ("ACCTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_SETTLEMENTPAYMENTMV" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_SETTLEMENTPAYMENTMV_DUEDAY" ON "TX"."SETTLEMENTPAYMENTMV" ("DUEDAY", "ACCTID") 
CREATE INDEX "TX"."IDX_SETTLEMENTPAYMENTMV_DUEDAY" ON "TX"."SETTLEMENTPAYMENTMV" ("DUEDAY", "ACCTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_SETTLEMENTPAYMENTMV_DUEDAY" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_CIITEM" ON "TX"."CIITEM" ("TERMID", "DEVICE", "POS", "NOTEID", "CCY", "DENOM", "REV") 
CREATE UNIQUE INDEX "TX"."PK_CIITEM" ON "TX"."CIITEM" ("TERMID", "DEVICE", "POS", "NOTEID", "CCY", "DENOM", "REV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_CIITEM" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_EXCSUBJECTREGISTRY" ON "TX"."EXCSUBJECTREGISTRY" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_EXCSUBJECTREGISTRY" ON "TX"."EXCSUBJECTREGISTRY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_SUBJECT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_EXCSUBJECTREGISTRY" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_TRANSLATION" ON "TX"."TRANSLATION" ("OWNERGUID", "OWNERPID", "PURPOSE") 
CREATE UNIQUE INDEX "TX"."PK_TRANSLATION" ON "TX"."TRANSLATION" ("OWNERGUID", "OWNERPID", "PURPOSE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 134 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_TRANSLATION" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_CREDITMGMTRULETRCHRVLCREDIT" ON "TX"."CREDITMGMTRULETRCHRVLCREDIT" ("STRATEGYTYPEID", "STATEID") 
CREATE UNIQUE INDEX "TX"."PK_CREDITMGMTRULETRCHRVLCREDIT" ON "TX"."CREDITMGMTRULETRCHRVLCREDIT" ("STRATEGYTYPEID", "STATEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_CREDITMGMTRULETRCHRVLCREDIT" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_TARIFFVERPARAM" ON "TX"."TARIFFVERPARAM" ("TARIFFVERID", "NAME") 
CREATE UNIQUE INDEX "TX"."PK_TARIFFVERPARAM" ON "TX"."TARIFFVERPARAM" ("TARIFFVERID", "NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_TARIFFVERPARAM" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_STATEMENTACCOMPANYINGTEXT" ON "TX"."STATEMENTACCOMPANYINGTEXT" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_STATEMENTACCOMPANYINGTEXT" ON "TX"."STATEMENTACCOMPANYINGTEXT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_STATEMENTACCOMPANYINGTEXT" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_LEXEME_ID" ON "TX"."LEXEME" ("KIND", "ID", "LANGCODE") 
CREATE INDEX "TX"."IDX_LEXEME_ID" ON "TX"."LEXEME" ("KIND", "ID", "LANGCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_LEXEME_ID" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_LEXEME" ON "TX"."LEXEME" ("ID", "OWNERCLASSID", "OWNERPROPID", "LANGCODE") 
CREATE UNIQUE INDEX "TX"."PK_LEXEME" ON "TX"."LEXEME" ("ID", "OWNERCLASSID", "OWNERPROPID", "LANGCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_LEXEME" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_RDX_PC_EVENTLIMITACC" ON "TX"."RDX_PC_EVENTLIMITACC" ("SUBSCRIPTIONID", "USERNAME", "EVENTCODE", "CHANNELKIND") 
CREATE UNIQUE INDEX "TX"."PK_RDX_PC_EVENTLIMITACC" ON "TX"."RDX_PC_EVENTLIMITACC" ("SUBSCRIPTIONID", "USERNAME", "EVENTCODE", "CHANNELKIND") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."PK_RDX_PC_EVENTLIMITACC" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_EXTAUTHAPPTOKENPRODUCT_INT" ON "TX"."EXTAUTHAPPTOKENPRODUCT" ("OUTINTERFACEID") 
CREATE INDEX "TX"."IDX_EXTAUTHAPPTOKENPRODUCT_INT" ON "TX"."EXTAUTHAPPTOKENPRODUCT" ("OUTINTERFACEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_EXTAUTHAPPTOKENPRODUCT_INT" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_EXTAUTHAPPTOKENPRODUCT" ON "TX"."EXTAUTHAPPTOKENPRODUCT" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_EXTAUTHAPPTOKENPRODUCT" ON "TX"."EXTAUTHAPPTOKENPRODUCT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_EXTAUTHAPPTOKENPRODUCT" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_TRCHRVLCRDQUALLEVEL" ON "TX"."TRCHRVLCRDQUALLEVEL" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_TRCHRVLCRDQUALLEVEL" ON "TX"."TRCHRVLCRDQUALLEVEL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_TRCHRVLCRDQUALLEVEL" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_TRCHRVLCRDQUALLEVEL_BASEQU" ON "TX"."TRCHRVLCRDQUALLEVEL" ("BASEQUALLEVELID") 
CREATE INDEX "TX"."IDX_TRCHRVLCRDQUALLEVEL_BASEQU" ON "TX"."TRCHRVLCRDQUALLEVEL" ("BASEQUALLEVELID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_TRCHRVLCRDQUALLEVEL_BASEQU" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_TRCHRVLCRDQUALLEVEL_CONTRA" ON "TX"."TRCHRVLCRDQUALLEVEL" ("CONTRACTTYPEID") 
CREATE INDEX "TX"."IDX_TRCHRVLCRDQUALLEVEL_CONTRA" ON "TX"."TRCHRVLCRDQUALLEVEL" ("CONTRACTTYPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_TRCHRVLCRDQUALLEVEL_CONTRA" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_RCDETECTOR" ON "TX"."RCDETECTOR" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_RCDETECTOR" ON "TX"."RCDETECTOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_RCDETECTOR" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_NETCHANNELTERM" ON "TX"."NETCHANNELTERM" ("CHANNELID") 
CREATE UNIQUE INDEX "TX"."PK_NETCHANNELTERM" ON "TX"."NETCHANNELTERM" ("CHANNELID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_NETCHANNELTERM" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_NETCHANNELTERM_TERMID" ON "TX"."NETCHANNELTERM" ("TERMID") 
CREATE INDEX "TX"."IDX_NETCHANNELTERM_TERMID" ON "TX"."NETCHANNELTERM" ("TERMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_NETCHANNELTERM_TERMID" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_PERSONEDUCATIONTYPE_RID" ON "TX"."PERSONEDUCATIONTYPE" ("RID") 
CREATE INDEX "TX"."IDX_PERSONEDUCATIONTYPE_RID" ON "TX"."PERSONEDUCATIONTYPE" ("RID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_PERSONEDUCATIONTYPE_RID" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_PERSONEDUCATIONTYPE" ON "TX"."PERSONEDUCATIONTYPE" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_PERSONEDUCATIONTYPE" ON "TX"."PERSONEDUCATIONTYPE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_PERSONEDUCATIONTYPE" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."IDX_RELEASEFEATURE_FEATURE" ON "TX"."INACTIVERELEASEFEATURE" ("INTERFACEID", "RELEASEFEATURE") 
CREATE UNIQUE INDEX "TX"."IDX_RELEASEFEATURE_FEATURE" ON "TX"."INACTIVERELEASEFEATURE" ("INTERFACEID", "RELEASEFEATURE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_RELEASEFEATURE_FEATURE" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_INACTIVERELEASEFEATURE" ON "TX"."INACTIVERELEASEFEATURE" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_INACTIVERELEASEFEATURE" ON "TX"."INACTIVERELEASEFEATURE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_INACTIVERELEASEFEATURE" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_BATCHJOB_RID" ON "TX"."BATCHJOB" ("RID") 
CREATE INDEX "TX"."IDX_BATCHJOB_RID" ON "TX"."BATCHJOB" ("RID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS" parallel 8
 ;
  ALTER INDEX "TX"."IDX_BATCHJOB_RID" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_BATCHJOB" ON "TX"."BATCHJOB" ("BATCHID", "THREADHASH", "ID") 
CREATE UNIQUE INDEX "TX"."PK_BATCHJOB" ON "TX"."BATCHJOB" ("BATCHID", "THREADHASH", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS" parallel 8
 ;
  ALTER INDEX "TX"."PK_BATCHJOB" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_BATCHJOB_BATCHSTATE" ON "TX"."BATCHJOB" ("BATCHID", "ISPROCESSED", "ID", "KIND", "THREADHASH") 
CREATE INDEX "TX"."IDX_BATCHJOB_BATCHSTATE" ON "TX"."BATCHJOB" ("BATCHID", "ISPROCESSED", "ID", "KIND", "THREADHASH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS" parallel 8
 ;
  ALTER INDEX "TX"."IDX_BATCHJOB_BATCHSTATE" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_CONTRACTTRANCHEDELTA" ON "TX"."CONTRACTTRANCHEDELTA" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_CONTRACTTRANCHEDELTA" ON "TX"."CONTRACTTRANCHEDELTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_CONTRACTTRANCHEDELTA" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_CONTRACTTRANCHEDELTA_ENTRY" ON "TX"."CONTRACTTRANCHEDELTA" ("ENTRYTRANID", "ENTRYSEQ") 
CREATE INDEX "TX"."IDX_CONTRACTTRANCHEDELTA_ENTRY" ON "TX"."CONTRACTTRANCHEDELTA" ("ENTRYTRANID", "ENTRYSEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_CONTRACTTRANCHEDELTA_ENTRY" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_CONTRACTTRANCHEDELTA_TRANC" ON "TX"."CONTRACTTRANCHEDELTA" ("TRANCHEID") 
CREATE INDEX "TX"."IDX_CONTRACTTRANCHEDELTA_TRANC" ON "TX"."CONTRACTTRANCHEDELTA" ("TRANCHEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_CONTRACTTRANCHEDELTA_TRANC" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_CONTRACTTRANCHEDELTA_OWNER" ON "TX"."CONTRACTTRANCHEDELTA" ("OWNERTRANID") 
CREATE INDEX "TX"."IDX_CONTRACTTRANCHEDELTA_OWNER" ON "TX"."CONTRACTTRANCHEDELTA" ("OWNERTRANID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_CONTRACTTRANCHEDELTA_OWNER" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_TERMTRACE" ON "TX"."TERMTRACE" ("TERMID", "ID") 
CREATE UNIQUE INDEX "TX"."PK_TERMTRACE" ON "TX"."TERMTRACE" ("TERMID", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_TERMTRACE" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_TERMTRACE_TIME" ON "TX"."TERMTRACE" ("TERMID", "TIME", "ID") 
CREATE INDEX "TX"."IDX_TERMTRACE_TIME" ON "TX"."TERMTRACE" ("TERMID", "TIME", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_TERMTRACE_TIME" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_RDX_JS_THREADEDJOBPARAM" ON "TX"."RDX_JS_THREADEDJOBPARAM" ("JOBDUETIME", "JOBID", "NAME") 
CREATE UNIQUE INDEX "TX"."PK_RDX_JS_THREADEDJOBPARAM" ON "TX"."RDX_JS_THREADEDJOBPARAM" ("JOBDUETIME", "JOBID", "NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX"  LOCAL
 (PARTITION "RDX_JS_THREADEDJOBPARAM_0" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" , 
 PARTITION "SYS_P646031" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" , 
 PARTITION "SYS_P646038" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" ) parallel 8
 ;
  ALTER INDEX "TX"."PK_RDX_JS_THREADEDJOBPARAM" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_DEVICE_MODEL" ON "TX"."DEVICE" ("MODELID", "STATUS", "ID") 
CREATE INDEX "TX"."IDX_DEVICE_MODEL" ON "TX"."DEVICE" ("MODELID", "STATUS", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_DEVICE_MODEL" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_DEVICE_TERMINAL" ON "TX"."DEVICE" ("TERMID") 
CREATE INDEX "TX"."IDX_DEVICE_TERMINAL" ON "TX"."DEVICE" ("TERMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_DEVICE_TERMINAL" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_DEVICE_PARENT" ON "TX"."DEVICE" ("PARTOFDEVICEID") 
CREATE INDEX "TX"."IDX_DEVICE_PARENT" ON "TX"."DEVICE" ("PARTOFDEVICEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_DEVICE_PARENT" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_DEVICE_CHOICE" ON "TX"."DEVICE" ("INSTID", "MODELID", "STATUS", "ID") 
CREATE INDEX "TX"."IDX_DEVICE_CHOICE" ON "TX"."DEVICE" ("INSTID", "MODELID", "STATUS", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_DEVICE_CHOICE" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_DEVICE" ON "TX"."DEVICE" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_DEVICE" ON "TX"."DEVICE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_DEVICE" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_RDX_NETCHANNELVAR" ON "TX"."RDX_NETCHANNELVAR" ("NETCHANNELID") 
CREATE UNIQUE INDEX "TX"."PK_RDX_NETCHANNELVAR" ON "TX"."RDX_NETCHANNELVAR" ("NETCHANNELID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."PK_RDX_NETCHANNELVAR" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."IDX_RESERVERATERULE_SEQ" ON "TX"."RESERVERATERULE" ("STRATEGYTYPEID", "SEQ") 
CREATE UNIQUE INDEX "TX"."IDX_RESERVERATERULE_SEQ" ON "TX"."RESERVERATERULE" ("STRATEGYTYPEID", "SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_RESERVERATERULE_SEQ" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_RESERVERATERULE" ON "TX"."RESERVERATERULE" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_RESERVERATERULE" ON "TX"."RESERVERATERULE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_RESERVERATERULE" NOPARALLEL;








prompt CREATE INDEX "TX"."IDX_CASOPERHANDLER_GENACCTROL1" ON "TX"."CASOPERHANDLER" ("CASGUID", "GENERICACCTROLENAME1") 
CREATE INDEX "TX"."IDX_CASOPERHANDLER_GENACCTROL1" ON "TX"."CASOPERHANDLER" ("CASGUID", "GENERICACCTROLENAME1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_CASOPERHANDLER_GENACCTROL1" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_CASOPERHANDLER_CORACCTMAP" ON "TX"."CASOPERHANDLER" ("CORRESPONDACCTMAPGUID") 
CREATE INDEX "TX"."IDX_CASOPERHANDLER_CORACCTMAP" ON "TX"."CASOPERHANDLER" ("CORRESPONDACCTMAPGUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_CASOPERHANDLER_CORACCTMAP" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_CASOPERHANDLER_OWNFUNDSROL" ON "TX"."CASOPERHANDLER" ("CASGUID", "OWNFUNDSACCTROLENAME") 
CREATE INDEX "TX"."IDX_CASOPERHANDLER_OWNFUNDSROL" ON "TX"."CASOPERHANDLER" ("CASGUID", "OWNFUNDSACCTROLENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_CASOPERHANDLER_OWNFUNDSROL" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_CASOPERHANDLER" ON "TX"."CASOPERHANDLER" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_CASOPERHANDLER" ON "TX"."CASOPERHANDLER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_CASOPERHANDLER" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_CASOPERHANDLER_EXPENSEAROL" ON "TX"."CASOPERHANDLER" ("CASGUID", "EXPENSEACCTROLENAME") 
CREATE INDEX "TX"."IDX_CASOPERHANDLER_EXPENSEAROL" ON "TX"."CASOPERHANDLER" ("CASGUID", "EXPENSEACCTROLENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_CASOPERHANDLER_EXPENSEAROL" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_CASOPERHANDLER_CASOPER" ON "TX"."CASOPERHANDLER" ("CASGUID", "FINOPERKIND", "FINOPERDIR") 
CREATE INDEX "TX"."IDX_CASOPERHANDLER_CASOPER" ON "TX"."CASOPERHANDLER" ("CASGUID", "FINOPERKIND", "FINOPERDIR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_CASOPERHANDLER_CASOPER" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_CASOPERHANDLER_INCACCTROLE" ON "TX"."CASOPERHANDLER" ("CASGUID", "INCACCTROLENAME") 
CREATE INDEX "TX"."IDX_CASOPERHANDLER_INCACCTROLE" ON "TX"."CASOPERHANDLER" ("CASGUID", "INCACCTROLENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_CASOPERHANDLER_INCACCTROLE" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_CASOPERHANDLER_EXPACCTROLE" ON "TX"."CASOPERHANDLER" ("CASGUID", "EXPACCTROLENAME") 
CREATE INDEX "TX"."IDX_CASOPERHANDLER_EXPACCTROLE" ON "TX"."CASOPERHANDLER" ("CASGUID", "EXPACCTROLENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_CASOPERHANDLER_EXPACCTROLE" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_CASOPERHANDLER_GENACCTROL2" ON "TX"."CASOPERHANDLER" ("CASGUID", "GENERICACCTROLENAME2") 
CREATE INDEX "TX"."IDX_CASOPERHANDLER_GENACCTROL2" ON "TX"."CASOPERHANDLER" ("CASGUID", "GENERICACCTROLENAME2") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_CASOPERHANDLER_GENACCTROL2" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_CASOPERHANDLER_RESACCTROLE" ON "TX"."CASOPERHANDLER" ("CASGUID", "RESACCTROLENAME") 
CREATE INDEX "TX"."IDX_CASOPERHANDLER_RESACCTROLE" ON "TX"."CASOPERHANDLER" ("CASGUID", "RESACCTROLENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_CASOPERHANDLER_RESACCTROLE" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_CASOPERHANDLER_OVERPAYAROL" ON "TX"."CASOPERHANDLER" ("CASGUID", "OVERPAYACCTROLE") 
CREATE INDEX "TX"."IDX_CASOPERHANDLER_OVERPAYAROL" ON "TX"."CASOPERHANDLER" ("CASGUID", "OVERPAYACCTROLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_CASOPERHANDLER_OVERPAYAROL" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_CASOPERHANDLER_ACCTCCY" ON "TX"."CASOPERHANDLER" ("ACCOUNTCCY") 
CREATE INDEX "TX"."IDX_CASOPERHANDLER_ACCTCCY" ON "TX"."CASOPERHANDLER" ("ACCOUNTCCY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_CASOPERHANDLER_ACCTCCY" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_SUBJECTTYPE" ON "TX"."SUBJECTTYPE" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_SUBJECTTYPE" ON "TX"."SUBJECTTYPE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_SUBJECT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_SUBJECTTYPE" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_SUBJECTTYPE_PARENT" ON "TX"."SUBJECTTYPE" ("PARENTID") 
CREATE INDEX "TX"."IDX_SUBJECTTYPE_PARENT" ON "TX"."SUBJECTTYPE" ("PARENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_SUBJECT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_SUBJECTTYPE_PARENT" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_DEVICEAPP" ON "TX"."DEVICEAPP" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_DEVICEAPP" ON "TX"."DEVICEAPP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_DEVICEAPP" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_DEVICEAPP_USERGUID" ON "TX"."DEVICEAPP" ("INSTID", "USERGUID", "URI") 
CREATE INDEX "TX"."IDX_DEVICEAPP_USERGUID" ON "TX"."DEVICEAPP" ("INSTID", "USERGUID", "URI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 83 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_DEVICEAPP_USERGUID" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_NETWORKREGIONCOUNTRY" ON "TX"."NETWORKREGIONCOUNTRY" ("NETWORKID", "COUNTRYID") 
CREATE UNIQUE INDEX "TX"."PK_NETWORKREGIONCOUNTRY" ON "TX"."NETWORKREGIONCOUNTRY" ("NETWORKID", "COUNTRYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_NETWORKREGIONCOUNTRY" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_NETWORKREGIONCOUNTRY_REGIO" ON "TX"."NETWORKREGIONCOUNTRY" ("NETWORKID", "REGID", "COUNTRYID") 
CREATE INDEX "TX"."IDX_NETWORKREGIONCOUNTRY_REGIO" ON "TX"."NETWORKREGIONCOUNTRY" ("NETWORKID", "REGID", "COUNTRYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_NETWORKREGIONCOUNTRY_REGIO" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_ISSUERECONDIFFTIER" ON "TX"."ISSUERECONDIFFTIER" ("TYPEID", "CCY", "SIGN", "LOWBOUND") 
CREATE UNIQUE INDEX "TX"."PK_ISSUERECONDIFFTIER" ON "TX"."ISSUERECONDIFFTIER" ("TYPEID", "CCY", "SIGN", "LOWBOUND") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."PK_ISSUERECONDIFFTIER" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_NS_MC_IP0050T1" ON "TX"."NS_MC_IP0050T1" ("NETWORKSTRUCTUREVERID", "MEMBERID", "SERVICEID", "REFERENCECODE", "CRITERIAID", "INPUTSOURCEID", "EFFECTIVETIMESTAMP") 
CREATE UNIQUE INDEX "TX"."PK_NS_MC_IP0050T1" ON "TX"."NS_MC_IP0050T1" ("NETWORKSTRUCTUREVERID", "MEMBERID", "SERVICEID", "REFERENCECODE", "CRITERIAID", "INPUTSOURCEID", "EFFECTIVETIMESTAMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_NS_MC_IP0050T1" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_DBS_SERVICEDRIVER" ON "TX"."ISO8583INTERFACEUNIT" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_DBS_SERVICEDRIVER" ON "TX"."ISO8583INTERFACEUNIT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_DBS_SERVICEDRIVER" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_ISO8583INTERFACEUNIT_ININT" ON "TX"."ISO8583INTERFACEUNIT" ("ININTERFACE", "ID") 
CREATE INDEX "TX"."IDX_ISO8583INTERFACEUNIT_ININT" ON "TX"."ISO8583INTERFACEUNIT" ("ININTERFACE", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_ISO8583INTERFACEUNIT_ININT" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_ISO8583UNIT_SYNCSYSTEM" ON "TX"."ISO8583INTERFACEUNIT" ("SYNCSYSTEMID") 
CREATE INDEX "TX"."IDX_ISO8583UNIT_SYNCSYSTEM" ON "TX"."ISO8583INTERFACEUNIT" ("SYNCSYSTEMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_ISO8583UNIT_SYNCSYSTEM" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_ISO8583INTERFACEUNIT_OUTIN" ON "TX"."ISO8583INTERFACEUNIT" ("OUTINTERFACE", "ID") 
CREATE INDEX "TX"."IDX_ISO8583INTERFACEUNIT_OUTIN" ON "TX"."ISO8583INTERFACEUNIT" ("OUTINTERFACE", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_ISO8583INTERFACEUNIT_OUTIN" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_TCTRANEXEC_TCID" ON "TX"."TESTCASETRANSITIONEXECUTION" ("TESTCASEID") 
CREATE INDEX "TX"."IDX_TCTRANEXEC_TCID" ON "TX"."TESTCASETRANSITIONEXECUTION" ("TESTCASEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_TCTRANEXEC_TCID" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_TCTRANEXEC_PREVCAS" ON "TX"."TESTCASETRANSITIONEXECUTION" ("PREVCASGUID") 
CREATE INDEX "TX"."IDX_TCTRANEXEC_PREVCAS" ON "TX"."TESTCASETRANSITIONEXECUTION" ("PREVCASGUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_TCTRANEXEC_PREVCAS" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_TCTRANEXEC_TRANSITIONID" ON "TX"."TESTCASETRANSITIONEXECUTION" ("TRANSITIONID") 
CREATE INDEX "TX"."IDX_TCTRANEXEC_TRANSITIONID" ON "TX"."TESTCASETRANSITIONEXECUTION" ("TRANSITIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_TCTRANEXEC_TRANSITIONID" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_TESTCASETRANSITIONEXECUTION" ON "TX"."TESTCASETRANSITIONEXECUTION" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_TESTCASETRANSITIONEXECUTION" ON "TX"."TESTCASETRANSITIONEXECUTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_TESTCASETRANSITIONEXECUTION" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_TCTRANEXEC_TCEXECID" ON "TX"."TESTCASETRANSITIONEXECUTION" ("TESTCASEEXECUTIONID") 
CREATE INDEX "TX"."IDX_TCTRANEXEC_TCEXECID" ON "TX"."TESTCASETRANSITIONEXECUTION" ("TESTCASEEXECUTIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_TCTRANEXEC_TCEXECID" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_CREDITLINEMP" ON "TX"."CREDITLINEMP" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_CREDITLINEMP" ON "TX"."CREDITLINEMP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."PK_CREDITLINEMP" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_CREDITLINEMP_BASECCY" ON "TX"."CREDITLINEMP" ("BASECCY") 
CREATE INDEX "TX"."IDX_CREDITLINEMP_BASECCY" ON "TX"."CREDITLINEMP" ("BASECCY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_CREDITLINEMP_BASECCY" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_CREDITLINEMP_CONTRACTTYPE" ON "TX"."CREDITLINEMP" ("CONTRACTTYPEID") 
CREATE INDEX "TX"."IDX_CREDITLINEMP_CONTRACTTYPE" ON "TX"."CREDITLINEMP" ("CONTRACTTYPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_CREDITLINEMP_CONTRACTTYPE" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_RDX_CACHEDENTITYCHILDGROUP" ON "TX"."RDX_CACHEDENTITYCHILDGROUP" ("INSTANCEID", "ENTITYID", "ENTITYPID", "GROUPID") 
CREATE UNIQUE INDEX "TX"."PK_RDX_CACHEDENTITYCHILDGROUP" ON "TX"."RDX_CACHEDENTITYCHILDGROUP" ("INSTANCEID", "ENTITYID", "ENTITYPID", "GROUPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."PK_RDX_CACHEDENTITYCHILDGROUP" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_RDX_JS_EVENTSCHD" ON "TX"."RDX_JS_EVENTSCHD" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_RDX_JS_EVENTSCHD" ON "TX"."RDX_JS_EVENTSCHD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."PK_RDX_JS_EVENTSCHD" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_CARDPRODUCTPANRANGE" ON "TX"."CARDPRODUCTPANRANGE" ("PRODUCTID", "ID") 
CREATE UNIQUE INDEX "TX"."PK_CARDPRODUCTPANRANGE" ON "TX"."CARDPRODUCTPANRANGE" ("PRODUCTID", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_CARDPRODUCTPANRANGE" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_TERMSETTINGSUDT" ON "TX"."TERMSETTINGSUDT" ("TERMSETTINGSID", "UDTTYPERID") 
CREATE UNIQUE INDEX "TX"."PK_TERMSETTINGSUDT" ON "TX"."TERMSETTINGSUDT" ("TERMSETTINGSID", "UDTTYPERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_TERMSETTINGSUDT" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_COFCONSENT" ON "TX"."COFCONSENT" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_COFCONSENT" ON "TX"."COFCONSENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_COFCONSENT" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_COFCONSENT_TOKEN" ON "TX"."COFCONSENT" ("TOKENID", "TERMOWNERRID") 
CREATE INDEX "TX"."IDX_COFCONSENT_TOKEN" ON "TX"."COFCONSENT" ("TOKENID", "TERMOWNERRID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_COFCONSENT_TOKEN" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_SETTLECONTRACT_C2R_ISSUE" ON "TX"."SETTLECONTRACT" ("CLEARRECONISSUETYPEID") 
CREATE INDEX "TX"."IDX_SETTLECONTRACT_C2R_ISSUE" ON "TX"."SETTLECONTRACT" ("CLEARRECONISSUETYPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_SETTLECONTRACT_C2R_ISSUE" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_SETTLECONTRACT_AGENTINST" ON "TX"."SETTLECONTRACT" ("AGENTINSTID") 
CREATE INDEX "TX"."IDX_SETTLECONTRACT_AGENTINST" ON "TX"."SETTLECONTRACT" ("AGENTINSTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_SETTLECONTRACT_AGENTINST" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_SETTLECONTRACT_S2C_ISSUE" ON "TX"."SETTLECONTRACT" ("SETTLECORRESPISSUETYPEID") 
CREATE INDEX "TX"."IDX_SETTLECONTRACT_S2C_ISSUE" ON "TX"."SETTLECONTRACT" ("SETTLECORRESPISSUETYPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_SETTLECONTRACT_S2C_ISSUE" NOPARALLEL;




prompt CREATE UNIQUE INDEX "TX"."PK_SETTLECONTRACT" ON "TX"."SETTLECONTRACT" ("ID") 
CREATE UNIQUE INDEX "TX"."PK_SETTLECONTRACT" ON "TX"."SETTLECONTRACT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."PK_SETTLECONTRACT" NOPARALLEL;


prompt CREATE INDEX "TX"."IDX_TRANPLAN_EXEC" ON "TX"."TRANPLAN" ("INSTID", "ISACTIVE", "REMAINCNT", "LASTINSTANCEDATE", "CONTRACTID", "PRIORITY" DESC, "ID") 
CREATE INDEX "TX"."IDX_TRANPLAN_EXEC" ON "TX"."TRANPLAN" ("INSTID", "ISACTIVE", "REMAINCNT", "LASTINSTANCEDATE", "CONTRACTID", "PRIORITY" DESC, "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "RBS_CONTRACT_IDX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_TRANPLAN_EXEC" NOPARALLEL;




prompt CREATE INDEX "TX"."IDX_RDX_PC_SENTMESSAGE_ADDR2" ON "TX"."RDX_PC_SENTMESSAGE" ("ERRORFLAG", "CHANNELID", "ADDRESS", "SENTTIME") 
CREATE INDEX "TX"."IDX_RDX_PC_SENTMESSAGE_ADDR2" ON "TX"."RDX_PC_SENTMESSAGE" ("ERRORFLAG", "CHANNELID", "ADDRESS", "SENTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 165 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RADIX" parallel 8
 ;
  ALTER INDEX "TX"."IDX_RDX_PC_SENTMESSAGE_ADDR2" NOPARALLEL;

spool off;


