spool ddl_constraint_trzsp_dem.lst
prompt - ddl_constraint_trzsp_dem
set time on timi on-- CONNECT SYSTEM
ALTER SESSION SET EVENTS '10150 TRACE NAME CONTEXT FOREVER, LEVEL 1';
ALTER SESSION SET EVENTS '10904 TRACE NAME CONTEXT FOREVER, LEVEL 1';
ALTER SESSION SET EVENTS '25475 TRACE NAME CONTEXT FOREVER, LEVEL 1';
ALTER SESSION SET EVENTS '10407 TRACE NAME CONTEXT FOREVER, LEVEL 1';
ALTER SESSION SET EVENTS '10851 TRACE NAME CONTEXT FOREVER, LEVEL 1';
ALTER SESSION SET EVENTS '22830 TRACE NAME CONTEXT FOREVER, LEVEL 192 ';
-- new object type path: TABLE_EXPORT/TABLE/CONSTRAINT/CONSTRAINT


prompt ALTER TABLE "TX"."DOEREXTMSG" ADD CONSTRAINT "PK_DOEREXTMSG" PRIMARY KEY ("TRANID", "DOERSEQ") RELY
ALTER TABLE "TX"."DOEREXTMSG" ADD CONSTRAINT "PK_DOEREXTMSG" PRIMARY KEY ("TRANID", "DOERSEQ") RELY
  USING INDEX "TX"."PK_DOEREXTMSG"  ENABLE NOVALIDATE;
-- new object type path: TABLE_EXPORT/TABLE/CONSTRAINT/REF_CONSTRAINT


prompt ALTER TABLE "TX"."DOEREXTMSG" ADD CONSTRAINT "FK_DOEREXTMSG_DOER" FOREIGN KEY ("TRANID", "DOERSEQ")
ALTER TABLE "TX"."DOEREXTMSG" ADD CONSTRAINT "FK_DOEREXTMSG_DOER" FOREIGN KEY ("TRANID", "DOERSEQ")
	  REFERENCES "TX"."DOER" ("TRANID", "SEQ") RELY DISABLE;


prompt ALTER TABLE "TX"."DOEREXTMSG" ADD CONSTRAINT "FK_DOEREXTMSG_TRAN" FOREIGN KEY ("TRANID")
ALTER TABLE "TX"."DOEREXTMSG" ADD CONSTRAINT "FK_DOEREXTMSG_TRAN" FOREIGN KEY ("TRANID")
	  REFERENCES "TX"."TRAN" ("ID") RELY DISABLE;

spool off;