

ASM

ALTER DISKGROUP DG_ASM DROP DISK 'DG_ASM000' REBALANCE POWER 20;




DATA

ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA0001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA0180001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA0190001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA0200001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA0210001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA0220001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA0230001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA0240001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA0250001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA0260001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA0270001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA0280001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA0290001' REBALANCE POWER 20;

ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA1' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA100001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA110001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA120001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA130001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA140001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA150001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA160001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA170001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA180001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA190001' REBALANCE POWER 20;

ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA2' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA200001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA210001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA220001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA230001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA240001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA3' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA320008' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA330007' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA340006' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA350005' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA360004' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA370003' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA380002' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA390001' REBALANCE POWER 20;

ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA4' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_0048' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_0049' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_0050' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_0051' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_0052' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_0053' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_0054' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_0055' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_0056' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_0057' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_0058' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_0059' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_0060' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_0061' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_0062' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_10001' REBALANCE POWER 20;

ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_11001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_12001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_13001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_14001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_15001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_16001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_20001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_40001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_50001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_60001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_70001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_80001' REBALANCE POWER 20;
ALTER DISKGROUP DG_DATA DROP DISK 'DG_DATA_90001' REBALANCE POWER 20;




ENTRY

ALTER DISKGROUP DG_ENTRY DROP DISK 'DG_ENTRY000' REBALANCE POWER 20;
ALTER DISKGROUP DG_ENTRY DROP DISK 'DG_ENTRY0001' REBALANCE POWER 20;
ALTER DISKGROUP DG_ENTRY DROP DISK 'DG_ENTRY0002' REBALANCE POWER 20;
ALTER DISKGROUP DG_ENTRY DROP DISK 'DG_ENTRY001' REBALANCE POWER 20;
ALTER DISKGROUP DG_ENTRY DROP DISK 'DG_ENTRY002' REBALANCE POWER 20;
ALTER DISKGROUP DG_ENTRY DROP DISK 'DG_ENTRY003' REBALANCE POWER 20;
ALTER DISKGROUP DG_ENTRY DROP DISK 'DG_ENTRY004' REBALANCE POWER 20;
ALTER DISKGROUP DG_ENTRY DROP DISK 'DG_ENTRY005' REBALANCE POWER 20;





MODEL

ALTER DISKGROUP DG_MODEL DROP DISK 'DG_MODEL_0001' REBALANCE POWER 20;
ALTER DISKGROUP DG_MODEL DROP DISK 'DG_MODEL_0002' REBALANCE POWER 20;
ALTER DISKGROUP DG_MODEL DROP DISK 'DG_MODEL_0003' REBALANCE POWER 20;





REDO01

ALTER DISKGROUP DG_REDO01 DROP DISK 'DG_REDO1000' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO01 DROP DISK 'DG_REDO1001' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO01 DROP DISK 'DG_REDO1002' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO01 DROP DISK 'DG_REDO1003' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO01 DROP DISK 'DG_REDO1004' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO01 DROP DISK 'DG_REDO1005' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO01 DROP DISK 'DG_REDO1006' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO01 DROP DISK 'DG_REDO1007' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO01 DROP DISK 'DG_REDO1008' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO01 DROP DISK 'DG_REDO1009' REBALANCE POWER 20;   




REDO02

ALTER DISKGROUP DG_REDO02 DROP DISK 'DG_REDO2000' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO02 DROP DISK 'DG_REDO2001' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO02 DROP DISK 'DG_REDO2002' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO02 DROP DISK 'DG_REDO2003' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO02 DROP DISK 'DG_REDO2004' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO02 DROP DISK 'DG_REDO2005' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO02 DROP DISK 'DG_REDO2006' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO02 DROP DISK 'DG_REDO2007' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO02 DROP DISK 'DG_REDO2008' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO02 DROP DISK 'DG_REDO2009' REBALANCE POWER 20;   



REDO03

ALTER DISKGROUP DG_REDO03 DROP DISK 'DG_REDO3000' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO03 DROP DISK 'DG_REDO3001' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO03 DROP DISK 'DG_REDO3002' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO03 DROP DISK 'DG_REDO3003' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO03 DROP DISK 'DG_REDO3004' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO03 DROP DISK 'DG_REDO3005' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO03 DROP DISK 'DG_REDO3006' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO03 DROP DISK 'DG_REDO3007' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO03 DROP DISK 'DG_REDO3008' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO03 DROP DISK 'DG_REDO3009' REBALANCE POWER 20;   



REDO04

ALTER DISKGROUP DG_REDO04 DROP DISK 'DG_REDO4000' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO04 DROP DISK 'DG_REDO4001' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO04 DROP DISK 'DG_REDO4002' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO04 DROP DISK 'DG_REDO4003' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO04 DROP DISK 'DG_REDO4004' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO04 DROP DISK 'DG_REDO4005' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO04 DROP DISK 'DG_REDO4006' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO04 DROP DISK 'DG_REDO4007' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO04 DROP DISK 'DG_REDO4008' REBALANCE POWER 20;   
ALTER DISKGROUP DG_REDO04 DROP DISK 'DG_REDO4009' REBALANCE POWER 20;   


FRA

ALTER DISKGROUP FRA DROP DISK 'FRA000' REBALANCE POWER 20;         
ALTER DISKGROUP FRA DROP DISK 'FRA001' REBALANCE POWER 20;         
ALTER DISKGROUP FRA DROP DISK 'FRA002' REBALANCE POWER 20;         
ALTER DISKGROUP FRA DROP DISK 'FRA003' REBALANCE POWER 20;         
ALTER DISKGROUP FRA DROP DISK 'FRA004' REBALANCE POWER 20;         
ALTER DISKGROUP FRA DROP DISK 'FRA005' REBALANCE POWER 20;         
ALTER DISKGROUP FRA DROP DISK 'FRA006' REBALANCE POWER 20;         
