spool autoextend_TRZSP.sql
select 
   'alter database datafile '''||file_name||''' '||' autoextend on maxsize unlimited;'
from 
   dba_data_files
   union all 
   select 
   'alter database tempfile '''||file_name||''' '||' autoextend on maxsize unlimited;'
from 
   dba_temp_files;

spool off


*******************


spool resize_TRZSP.sql
select 
   'alter database datafile '''||file_name||''' '||'  RESIZE &2'||'G;'
from 
   dba_data_files
where tablespace_name =nvl('&tablespace_name', tablespace_name);
spool off



spool resize_TRZSP.sql
select 
   'alter database datafile '''||file_name||''' '||'  RESIZE &2'||'M;'
from 
   dba_data_files
where tablespace_name =nvl('&tablespace_name', tablespace_name);
spool off


*****************************

spool datafiles _TRZSP.sql
select 
   'alter database datafile '''||file_name||''' '||'  SIZE '|| bytes/1024/1024/1024 ||'G;'
from 
   dba_data_files
where tablespace_name =nvl('&tablespace_name', tablespace_name);
spool off



*****************************

ALTER TABLESPACE UNDOTBS3 ADD DATAFILE '+DATA_TRZSP' SIZE 1G AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE UNDOTBS3 ADD DATAFILE '+DATA_TRZSP' SIZE 1G AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE UNDOTBS3 ADD DATAFILE '+DATA_TRZSP' SIZE 1G AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE UNDOTBS3 ADD DATAFILE '+DATA_TRZSP' SIZE 1G AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE UNDOTBS3 ADD DATAFILE '+DATA_TRZSP' SIZE 1G AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE UNDOTBS3 ADD DATAFILE '+DATA_TRZSP' SIZE 1G AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE UNDOTBS3 ADD DATAFILE '+DATA_TRZSP' SIZE 1G AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE UNDOTBS3 ADD DATAFILE '+DATA_TRZSP' SIZE 1G AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE UNDOTBS3 ADD DATAFILE '+DATA_TRZSP' SIZE 1G AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE UNDOTBS3 ADD DATAFILE '+DATA_TRZSP' SIZE 1G AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE UNDOTBS3 ADD DATAFILE '+DATA_TRZSP' SIZE 1G AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE UNDOTBS3 ADD DATAFILE '+DATA_TRZSP' SIZE 1G AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE UNDOTBS3 ADD DATAFILE '+DATA_TRZSP' SIZE 1G AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE UNDOTBS3 ADD DATAFILE '+DATA_TRZSP' SIZE 1G AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE UNDOTBS3 ADD DATAFILE '+DATA_TRZSP' SIZE 1G AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE UNDOTBS3 ADD DATAFILE '+DATA_TRZSP' SIZE 1G AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE UNDOTBS3 ADD DATAFILE '+DATA_TRZSP' SIZE 1G AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE UNDOTBS3 ADD DATAFILE '+DATA_TRZSP' SIZE 1G AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE UNDOTBS3 ADD DATAFILE '+DATA_TRZSP' SIZE 1G AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE UNDOTBS3 ADD DATAFILE '+DATA_TRZSP' SIZE 1G AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;







*******************************


DROP


ALTER TABLESPACE RBS_DOER DROP DATAFILE '+DATA_TRZSP/TRZSP/DATAFILE/rbs_doer.959.1180408075';


select 
   'ALTER TABLESPACE '||tablespace_name||' DROP DATAFILE '|| file_id ||';'
from 
   dba_data_files
where tablespace_name =nvl('&tablespace_name', tablespace_name)
--and file_id >= 351
order by file_id;




************************
*******************************************************
************************
*********************************************************************************
************************
***************************************************************************************************

Sacas discos no usados de la base de datos NUEVA 


RBS_ACCOUNT_IDX
select 
   'alter database datafile '''||file_name||''' '||'  RESIZE '||'32767M;'
from 
   dba_data_files
where tablespace_name =nvl('&tablespace_name', tablespace_name);






ALTER TABLESPACE RBS_ACCOUNT_IDX ADD DATAFILE '+DATA_TRZSP' SIZE 32767M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE RBS_ACCOUNT_IDX ADD DATAFILE '+DATA_TRZSP' SIZE 32767M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE RBS_ACCOUNT_IDX ADD DATAFILE '+DATA_TRZSP' SIZE 32767M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE RBS_ACCOUNT_IDX ADD DATAFILE '+DATA_TRZSP' SIZE 32767M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;


****************************************
****************************************

select 
   'alter database datafile '''||file_name||''' '||'  RESIZE '||'15G;'
from 
   dba_data_files
where tablespace_name =nvl('&tablespace_name', tablespace_name);


CONCILIATION_DATA_SEP                5120       4163        957      18.69
CONCILIATION_DATA_OCT                7168       5955       1213      16.92

*********
*********

ALTER TABLESPACE RBS_ACCOUNT ADD DATAFILE '+DATA_TRZSP' SIZE 16383M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE RBS_ACCOUNT ADD DATAFILE '+DATA_TRZSP' SIZE 32767M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE RBS_ACCOUNT ADD DATAFILE '+DATA_TRZSP' SIZE 32767M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;

****VERIFICAR RBS_POSTING 9% free 

RBS_TOKEN                           20480   13176.38    7303.63      35.66
RBS_DOER                           420861  272447.88  148413.13      35.26
RESPONSECODESTADISTIC_DATA_SEP       3072       2051       1021      33.24
ACCOUNTING_DATA_OCT                  3072       2179        893      29.07

Name                            Size (MB)  Used (MB)  Free (MB)     % Free
------------------------------ ---------- ---------- ---------- ----------
ACCOUNTING_DATA_SEP                  3072       2307        765       24.9
TRAN_DATA_SEP                       46080      35118      10962      23.79
RBS_TRAN                          1015802     813837     201965      19.88
RBS_SUBJECT                         10240    8252.75    1987.25      19.41
RBS_ENTRY                           40960    33031.5     7928.5      19.36
RBS_POSTING                        122880  111323.38   11556.63        9.4
RBS_ACCOUNT                         98301   98227.19      73.81        .08


ALTER TABLESPACE RBS_POSTING ADD DATAFILE '+DATA_TRZSP' SIZE 32767M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;



**********************************************************************************

ALTER TABLESPACE RBS_DOER ADD DATAFILE '+DATA_TRZSP' SIZE 16383M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE RBS_DOER ADD DATAFILE '+DATA_TRZSP' SIZE 16383M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE RBS_DOER ADD DATAFILE '+DATA_TRZSP' SIZE 16383M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;


ALTER TABLESPACE RBS_DOER ADD DATAFILE '+DATA_TRZSP' SIZE 16383M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE RBS_DOER ADD DATAFILE '+DATA_TRZSP' SIZE 16383M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;





ALTER TABLESPACE RBS_DOER_IDX ADD DATAFILE '+DATA_TRZSP' SIZE 8200M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE RBS_DOER_IDX ADD DATAFILE '+DATA_TRZSP' SIZE 8200M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;



ALTER TABLESPACE RBS_DOER ADD DATAFILE '+DATA_TRZSP' SIZE 8200M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE RBS_DOER ADD DATAFILE '+DATA_TRZSP' SIZE 8200M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE RBS_DOER ADD DATAFILE '+DATA_TRZSP' SIZE 8200M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;




ALTER TABLESPACE RBS_TRAN ADD DATAFILE '+DATA_TRZSP' SIZE 16383M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE RBS_TRAN ADD DATAFILE '+DATA_TRZSP' SIZE 16383M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE RBS_TRAN ADD DATAFILE '+DATA_TRZSP' SIZE 16383M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE RBS_TRAN ADD DATAFILE '+DATA_TRZSP' SIZE 16383M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;
ALTER TABLESPACE RBS_TRAN ADD DATAFILE '+DATA_TRZSP' SIZE 16383M AUTOEXTEND ON NEXT 2G MAXSIZE UNLIMITED;

