# oracle19-database-preinstall-19c setting for nofile soft limit is 1024
oracle19 soft nofile 1024

# oracle19-database-preinstall-19c setting for nofile hard limit is 65536
oracle19 hard nofile 65536

# oracle19-database-preinstall-19c setting for nproc soft limit is 16384
# refer orabug15971421 for more info.
oracle19 soft nproc 16384

# oracle19-database-preinstall-19c setting for nproc hard limit is 16384
oracle19 hard nproc 16384

# oracle19-database-preinstall-19c setting for stack soft limit is 10240KB
oracle19 soft stack 10240

# oracle19-database-preinstall-19c setting for stack hard limit is 32768KB
oracle19 hard stack 32768

# oracle19-database-preinstall-19c setting for memlock hard limit is maximum of 128GB on x86_64 or 3GB on x86 OR 90 % of RAM
#oracle19 hard memlock 25165824
oracle hard memlock 29624433


# oracle19-database-preinstall-19c setting for memlock soft limit is maximum of 128GB on x86_64 or 3GB on x86 OR 90% of RAM
#oracle19 soft memlock 25165824
oracle soft memlock 29624433


# oracle19-database-preinstall-19c setting for data soft limit is 'unlimited'
oracle19 soft data unlimited

# oracle19-database-preinstall-19c setting for data hard limit is 'unlimited'
