set lin 180
col host_name format a32
select instance_name,LOGINS,host_name,status,DATABASE_STATUS,to_char(STARTUP_TIME,'dd-mm-yyyy hh24:mi:ss') from v$instance;
select to_char(sysdate,'dd-mm-yyyy hh24:mi:ss') from dual;
set time on;
set timing on;

prompt ---------------------------------------------------------------------------------;
show parameter db_name;
prompt ---------------------------------------------------------------------------------;
---ROLE DE ACCESO PLATAFORMA MEDIA
CREATE ROLE SEGURIDAD_INFORMATICA NOT IDENTIFIED;
GRANT DROP USER TO SEGURIDAD_INFORMATICA;
GRANT ALTER USER TO SEGURIDAD_INFORMATICA;
GRANT CREATE ROLE TO SEGURIDAD_INFORMATICA;
GRANT CREATE USER TO SEGURIDAD_INFORMATICA;
GRANT DROP PROFILE TO SEGURIDAD_INFORMATICA;
GRANT ALTER PROFILE TO SEGURIDAD_INFORMATICA;
--GRANT ALTER ANY SQL PROFILE TO SEGURIDAD_INFORMATICA;
GRANT CREATE PROFILE TO SEGURIDAD_INFORMATICA;
GRANT DROP ANY ROLE TO SEGURIDAD_INFORMATICA;
GRANT ALTER ANY ROLE TO SEGURIDAD_INFORMATICA;
GRANT CREATE SESSION TO SEGURIDAD_INFORMATICA;
GRANT GRANT ANY ROLE TO SEGURIDAD_INFORMATICA;
GRANT DROP ANY SYNONYM TO SEGURIDAD_INFORMATICA;
GRANT CREATE ANY SYNONYM TO SEGURIDAD_INFORMATICA;
GRANT DROP PUBLIC SYNONYM TO SEGURIDAD_INFORMATICA;
GRANT GRANT ANY PRIVILEGE TO SEGURIDAD_INFORMATICA;
GRANT CREATE PUBLIC SYNONYM TO SEGURIDAD_INFORMATICA;
GRANT SELECT ANY DICTIONARY TO SEGURIDAD_INFORMATICA;
GRANT GRANT ANY OBJECT PRIVILEGE TO SEGURIDAD_INFORMATICA;
GRANT CREATE PUBLIC DATABASE LINK TO SEGURIDAD_INFORMATICA;
GRANT SELECT_CATALOG_ROLE TO SEGURIDAD_INFORMATICA;
GRANT ALTER SESSION TO SEGURIDAD_INFORMATICA;
GRANT CREATE DATABASE LINK TO SEGURIDAD_INFORMATICA;
GRANT DROP PUBLIC DATABASE LINK TO SEGURIDAD_INFORMATICA;
GRANT CONNECT TO SEGURIDAD_INFORMATICA;
GRANT CREATE SYNONYM TO SEGURIDAD_INFORMATICA;
----GRANT UNLIMITED TABLESPACE TO SEGURIDAD_INFORMATICA;
GRANT SELECT ON  SYS.DBA_PROFILES TO SEGURIDAD_INFORMATICA;
GRANT SELECT ON  SYS.DBA_USERS TO SEGURIDAD_INFORMATICA;
--new
GRANT SELECT ON  SYS.DBA_ROLE_PRIVS TO SEGURIDAD_INFORMATICA;
---GRANT EXECUTE ON  SYS.DBMS_JOB TO SEGURIDAD_INFORMATICA;
---GRANT EXECUTE ON  SYS.DBMS_TRANSACTION TO SEGURIDAD_INFORMATICA;
GRANT SELECT ON  SYS.V_$SESSION TO SEGURIDAD_INFORMATICA;
GRANT SELECT ON  SYS.V_$SQL TO SEGURIDAD_INFORMATICA;
GRANT SELECT ON  SYS.V_$VERSION TO SEGURIDAD_INFORMATICA;
---GRANT SELECT ANY TABLE TO SEGURIDAD_INFORMATICA WITH ADMIN OPTION;
---GRANT DELETE ANY TABLE TO SEGURIDAD_INFORMATICA WITH ADMIN OPTION;
---GRANT INSERT ANY TABLE TO SEGURIDAD_INFORMATICA WITH ADMIN OPTION;
---GRANT UPDATE ANY TABLE TO SEGURIDAD_INFORMATICA WITH ADMIN OPTION;
GRANT DROP PROFILE TO SEGURIDAD_INFORMATICA;
GRANT ALTER PROFILE TO SEGURIDAD_INFORMATICA;
GRANT CREATE PROFILE TO SEGURIDAD_INFORMATICA;

--Para asignar el ROL al usuario NM se Perimetro
--ALTER USER NM_PERIMETRO DEFAULT ROLE AUDIT_SEGURIDAD;
--Nota: El usuario de perimetro que se designe debe contar con los siguientes privilegios de lo contrario no funciona el role
--GRANT AUDIT_SEGURIDAD TO NM_PERIMETRO WITH ADMIN OPTION;
--ALTER USER NM_PERIMETRO DEFAULT ROLE AUDIT_SEGURIDAD;

CREATE PROFILE BASICO LIMIT
  SESSIONS_PER_USER 1
  CPU_PER_SESSION DEFAULT
  CPU_PER_CALL DEFAULT
  CONNECT_TIME DEFAULT
  IDLE_TIME 10
  LOGICAL_READS_PER_SESSION DEFAULT
  LOGICAL_READS_PER_CALL DEFAULT
  COMPOSITE_LIMIT DEFAULT
  PRIVATE_SGA DEFAULT
  FAILED_LOGIN_ATTEMPTS 3
  PASSWORD_LIFE_TIME 25
  PASSWORD_REUSE_TIME 365
  PASSWORD_REUSE_MAX 20
  PASSWORD_LOCK_TIME 1
  PASSWORD_GRACE_TIME 3;
  --PASSWORD_VERIFY_FUNCTION bdv_verify_function;
--ALTER PROFILE basico LIMIT PASSWORD_VERIFY_FUNCTION bdv_verify_function;

--Alexis Moreno
CREATE USER NM05669
  IDENTIFIED BY "seguridad_01"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
GRANT CREATE SESSION TO NM05669;
GRANT CONNECT TO NM05669;
GRANT SEGURIDAD_INFORMATICA TO NM05669 WITH ADMIN OPTION;
ALTER USER NM05669 DEFAULT ROLE ALL;
ALTER USER NM05669 DEFAULT ROLE "SEGURIDAD_INFORMATICA";
--ALTER USER NM25361 PASSWORD EXPIRE;


--Korenia Volcan
CREATE USER NM25361
  IDENTIFIED BY "seguridad_01"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
GRANT CREATE SESSION TO NM25361;
GRANT CONNECT TO NM25361;
GRANT SEGURIDAD_INFORMATICA TO NM25361 WITH ADMIN OPTION;
ALTER USER NM25361 DEFAULT ROLE ALL;
ALTER USER NM25361 DEFAULT ROLE "SEGURIDAD_INFORMATICA";
--ALTER USER NM25361 PASSWORD EXPIRE;

-- Reynaldo Flores:
CREATE USER NM40465
  IDENTIFIED BY "seguridad_01"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
GRANT CREATE SESSION TO NM40465;
GRANT CONNECT TO NM40465;
GRANT SEGURIDAD_INFORMATICA TO NM40465 WITH ADMIN OPTION;
ALTER USER NM40465 DEFAULT ROLE ALL;
ALTER USER NM40465 DEFAULT ROLE "SEGURIDAD_INFORMATICA";



-- Erick Maza:
CREATE USER NM29099
  IDENTIFIED BY "seguridad_01"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
GRANT CREATE SESSION TO NM29099;
GRANT CONNECT TO NM29099;
GRANT SEGURIDAD_INFORMATICA TO NM29099 WITH ADMIN OPTION;
ALTER USER NM29099 DEFAULT ROLE ALL;
ALTER USER NM29099 DEFAULT ROLE "SEGURIDAD_INFORMATICA";

--Nesmary Rodriguez
CREATE USER NM29003
  IDENTIFIED BY "seguridad_01"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
GRANT CREATE SESSION TO NM29003;
GRANT CONNECT TO NM29003;
GRANT SEGURIDAD_INFORMATICA TO NM29003 WITH ADMIN OPTION;
ALTER USER NM29003 DEFAULT ROLE ALL;
ALTER USER NM29003 DEFAULT ROLE "SEGURIDAD_INFORMATICA";


prompt ---------------------------------------------------------------------------------;


--Para validar cuales usuarios ya existen ejecutar el siguiente query

--Para validar cuales usuarios ya existen ejecutar el siguiente query

COL USUARIO FOR A10
COL ESTATUS FOR A8
SELECT USERNAME AS USUARIO,
(CASE WHEN USERNAME='NM05669' THEN 'Alexis Moreno'
     WHEN USERNAME='NM25361' THEN 'Korenia Volcan'
     WHEN USERNAME='NM29099' THEN 'Erick Maza'
     WHEN USERNAME='NM40465' THEN 'Reynaldo Flores'
     --WHEN USERNAME='NM22241' THEN 'Gerardo Ramirez'
    END) NOMBRE, ACCOUNT_STATUS AS ESTATUS, CREATED AS CREADO
FROM DBA_USERS
WHERE USERNAME IN ('NM05669','NM25361','NM29099','NM40465');




