SESSION 0911-0912



******************************************
*******MV REBUILD DE IDX_PARTITIONS*******
******************************************
**DE RBS_POSTING_IDX A MANTENIMIENTOS_TX**
******************************************


ALTER INDEX TX.IDX_POSTINGARCH_ACCOUNTDAY REBUILD PARTITION POSTINGARCH_2024_08 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_POSTINGARCH_ACCOUNTDAY REBUILD PARTITION POSTINGARCH_2024_09 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_POSTINGARCH_ACCOUNTDAY REBUILD PARTITION POSTINGARCH_2024_10 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_05 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_06 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_07 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_08 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_09 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_10 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_11 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_12 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_13 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_14 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_15 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_16 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_17 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_18 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_19 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_20 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_21 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_05 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_06 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_07 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_08 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_09 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_10 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_11 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_12 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_13 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_14 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_15 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_16 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_17 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_18 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_19 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_20 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_21 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_POSTINGARCH REBUILD PARTITION POSTINGARCH_2024_08 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_POSTINGARCH REBUILD PARTITION POSTINGARCH_2024_09 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_POSTINGARCH REBUILD PARTITION POSTINGARCH_2024_10 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_05 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_06 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_07 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_08 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_09 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_10 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_11 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_12 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_13 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_14 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_15 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_16 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_17 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_18 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_19 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_20 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_21 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_05 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_06 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_07 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_08 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_09 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_10 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_11 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_12 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_13 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_14 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_15 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_16 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_17 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_18 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_19 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_20 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_21 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_05 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_06 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_07 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_08 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_09 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_10 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_11 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_12 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_13 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_14 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_15 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_16 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_17 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_18 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_19 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_20 TABLESPACE MANTENIMIENTOS_TX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_21 TABLESPACE MANTENIMIENTOS_TX;



******************************************
************RESIZE DE INDICES*************
******************************************
**DE RBS_POSTING_IDX A MANTENIMIENTOS_TX**
******************************************




alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.832.1132757939' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.839.1134142895' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.12369' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1044.1143642313' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1135.1159715949' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1270.1174746633' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.285.1098280883' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1084.1151926727' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1219.1173446747' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1284.1174752325' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1069.1149320733' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1122.1159707289' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1128.1159707439' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1142.1163967283' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.16789' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1272.1174747175' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.976.1139418865' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1025' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1265.1174570709' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1156.1168634765' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.816.1130594961' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1017.1139758439' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1043.1142692453' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1269.1174746579' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.887.1136801227' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1117.1155122223' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1118.1155981941' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1125.1159707369' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.862.1135516241' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.886.1136801027' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1150.1168633431' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1154.1168634487' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1178' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1274.1174747309' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.811.1128444211' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1058.1146043483' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1085.1153219591' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.729.1122817847' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1066.1148140653' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1271.1174746703' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1064.1147430473' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1083.1150641479' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1101.1153911515' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1136.1159716065' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1141.1163967195' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.398.1113179991' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1215.1173308647' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1089' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1121.1159707235' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1147.1166779373' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1148.1168633091' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1134.1159715925' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1149.1168633159' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1251.1174560533' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1255.1174562083' resize 10m;
alter database datafile '+DATA/TRZSP/DATAFILE/rbs_posting_idx.1280.1174751393' resize 10m;





******************************************
*********MV REBUILD DE INDICES************
******************************************
**DE RBS_POSTING_IDX A MANTENIMIENTOS_TX**
******************************************

ALTER INDEX TX.IDX_POSTINGARCH_ACCOUNTDAY REBUILD PARTITION POSTINGARCH_2024_08 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_POSTINGARCH_ACCOUNTDAY REBUILD PARTITION POSTINGARCH_2024_09 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_POSTINGARCH_ACCOUNTDAY REBUILD PARTITION POSTINGARCH_2024_10 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_05 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_06 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_07 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_08 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_09 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_10 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_11 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_12 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_13 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_14 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_15 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_16 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_17 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_18 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_19 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_20 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEHOLDACTION REBUILD PARTITION UNDONEHOLDACTION_2024_09_21 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_05 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_06 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_07 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_08 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_09 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_10 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_11 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_12 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_13 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_14 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_15 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_16 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_17 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_18 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_19 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_20 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_UNDONEPOSTING REBUILD PARTITION UNDONEPOSTING_2024_09_21 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_POSTINGARCH REBUILD PARTITION POSTINGARCH_2024_08 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_POSTINGARCH REBUILD PARTITION POSTINGARCH_2024_09 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_POSTINGARCH REBUILD PARTITION POSTINGARCH_2024_10 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_05 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_06 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_07 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_08 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_09 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_10 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_11 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_12 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_13 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_14 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_15 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_16 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_17 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_18 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_19 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_20 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.PK_HOLDACTION REBUILD PARTITION HOLDACTION_2024_09_21 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_05 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_06 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_07 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_08 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_09 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_10 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_11 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_12 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_13 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_14 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_15 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_16 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_17 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_18 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_19 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_20 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_UNDONEHOLDACTION_HOLD REBUILD PARTITION UNDONEHOLDACTION_2024_09_21 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_05 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_06 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_07 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_08 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_09 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_10 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_11 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_12 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_13 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_14 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_15 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_16 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_17 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_18 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_19 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_20 TABLESPACE RBS_POSTING_IDX;
ALTER INDEX TX.IDX_HOLDACTION_HOLD REBUILD PARTITION HOLDACTION_2024_09_21 TABLESPACE RBS_POSTING_IDX;
