#--Ver tablespace--#

SET PAGES 999
COL TABLESPACE_NAME FORMAT A40
COL "SIZE MB" FORMAT 999,999,999
COL "FREE MB" FORMAT 99,999,999
COL "% USED" FORMAT 999
SELECT TSU.TABLESPACE_NAME, CEIL(TSU.USED_MB) "SIZE MB"
, DECODE(CEIL(TSF.FREE_MB), NULL,0,CEIL(TSF.FREE_MB)) "FREE MB"
, DECODE(100 - CEIL(TSF.FREE_MB/TSU.USED_MB*100), NULL, 100,
               100 - CEIL(TSF.FREE_MB/TSU.USED_MB*100)) "% USED"
FROM (SELECT TABLESPACE_NAME, SUM(BYTES)/1024/1024 USED_MB
FROM DBA_DATA_FILES GROUP BY TABLESPACE_NAME UNION ALL
SELECT TABLESPACE_NAME || '  **TEMP**'
, SUM(BYTES)/1024/1024 USED_MB
FROM DBA_TEMP_FILES GROUP BY TABLESPACE_NAME) TSU
, (SELECT TABLESPACE_NAME, SUM(BYTES)/1024/1024 FREE_MB
FROM DBA_FREE_SPACE GROUP BY TABLESPACE_NAME) TSF
WHERE TSU.TABLESPACE_NAME = TSF.TABLESPACE_NAME (+)
--and TSU.TABLESPACE_NAME = 'DATA_IDENTITY_LOG'
ORDER BY 4
/

#--Ver datafiles de la BD--#

set linesize 4000
set pages 999
col FILE_NAME format a70
col FILE_ID format 999,990
col TABLESPACE_NAME format a35
col RELATIVE_FNO format 9999
select FILE_NAME,FILE_ID,TABLESPACE_NAME, bytes/1024/1024 MB, RELATIVE_FNO,AUTOEXTENSIBLE, status
from dba_data_files
where TABLESPACE_NAME in ('DATA_BDVNETP')
/





#--Ampliar o agregar datafile al tablespace--#

ALTER TABLESPACE SYSAUX ADD DATAFILE '+DATA/' SIZE 32767M AUTOEXTEND OFF;




#--Ampliar o modificar datafile al tablespace--#

ALTER DATABASE DATAFILE '+DATA/PRAFORCAQ/DATAFILE/sysaux.258.1173790127' RESIZE 32767M;