#!/bin/bash
rpm -qa | grep libaio-devel
rpm -qa | grep ksh
rpm -qa | grep elfutils-libelf-devel
rpm -qa | grep oracle-database-preinstall-19c
rpm -qa | grep device-mapper-multipath
rpm -qa | grep binutils
rpm -qa | grep gcc
rpm -qa | grep gcc-c++
rpm -qa | grep glibc
rpm -qa | grep glibc-devel
rpm -qa | grep libgcc
rpm -qa | grep libstdc++
rpm -qa | grep libstdc++-devel
rpm -qa | grep libaio
rpm -qa | grep libaio-devel
rpm -qa | grep libXext
rpm -qa | grep libXtst
rpm -qa | grep libX11
rpm -qa | grep libXau
rpm -qa | grep libxcb
rpm -qa | grep libXi
rpm -qa | grep make
rpm -qa | grep sysstat
rpm -qa | grep unixODBC
rpm -qa | grep unixODBC-devel
rpm -qa | grep zlib-devel
rpm -qa | grep elfutils-libelf-devel
rpm -qa | grep numactl
rpm -qa | grep rng-tools
rpm -qa | grep oracleasm
rpm -qa | grep kernel-uek-devel
rpm -qa | grep kmod-oracleasm
rpm -qa | grep libnsl
rpm -qa | grep libnsl.i686
rpm -qa | grep libnsl2
rpm -qa | grep libnsl2.i686
