GRANT SELECT ON V_$EVENT_NAME TO RCVRY;
GRANT SELECT ON V_$EVENTMETRIC TO RCVRY;
GRANT SELECT ON V_$LOCK TO RCVRY;
GRANT SELECT ON V_$OPEN_CURSOR TO RCVRY;
GRANT SELECT ON V_$PARAMETER TO RCVRY;
GRANT SELECT ON V_$PROCESS TO RCVRY;
GRANT SELECT ON V_$PX_SESSION TO RCVRY;
GRANT SELECT ON V_$ROLLNAME TO RCVRY;
GRANT SELECT ON V_$SESS_IO TO RCVRY;
GRANT SELECT ON V_$SESSION TO RCVRY;
GRANT SELECT ON V_$SESSION_CONNECT_INFO TO RCVRY;
GRANT SELECT ON V_$SESSION_EVENT TO RCVRY;
GRANT SELECT ON V_$SESSION_LONGOPS TO RCVRY;
GRANT SELECT ON V_$SESSION_WAIT TO RCVRY;
GRANT SELECT ON V_$SESSTAT TO RCVRY;
GRANT SELECT ON V_$SQL TO RCVRY;
GRANT SELECT ON V_$SQL_PLAN TO RCVRY;
GRANT SELECT ON V_$SQLTEXT_WITH_NEWLINES TO RCVRY;
GRANT SELECT ON V_$STATNAME TO RCVRY;
GRANT SELECT ON V_$TRANSACTION TO RCVRY;





