DROP USER BDVEMPP CASCADE;

CREATE USER BDVEMPP
  IDENTIFIED BY <password>
  DEFAULT TABLESPACE DATA
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

-- 3 Roles for BDVEMPP 
GRANT CONNECT TO BDVEMPP;
GRANT DATAPUMP_EXP_FULL_DATABASE TO BDVEMPP;
GRANT RESOURCE TO BDVEMPP;
ALTER USER BDVEMPP DEFAULT ROLE NONE;

-- 21 System Privileges for BDVEMPP 
GRANT ADVISOR TO BDVEMPP;
GRANT CREATE ANY INDEX TO BDVEMPP;
GRANT CREATE LIBRARY TO BDVEMPP;
GRANT CREATE MATERIALIZED VIEW TO BDVEMPP;
GRANT CREATE PROCEDURE TO BDVEMPP;
GRANT CREATE PUBLIC DATABASE LINK TO BDVEMPP;
GRANT CREATE PUBLIC SYNONYM TO BDVEMPP;
GRANT CREATE SEQUENCE TO BDVEMPP;
GRANT CREATE SESSION TO BDVEMPP;
GRANT CREATE SYNONYM TO BDVEMPP;
GRANT CREATE TABLE TO BDVEMPP;
GRANT CREATE TRIGGER TO BDVEMPP;
GRANT CREATE TYPE TO BDVEMPP;
GRANT CREATE VIEW TO BDVEMPP;
GRANT DEBUG ANY PROCEDURE TO BDVEMPP;
GRANT DEBUG CONNECT SESSION TO BDVEMPP;
GRANT DROP PUBLIC DATABASE LINK TO BDVEMPP;
GRANT EXECUTE ANY PROCEDURE TO BDVEMPP;
GRANT SELECT ANY SEQUENCE TO BDVEMPP;
GRANT SELECT ANY TABLE TO BDVEMPP;
GRANT UNLIMITED TABLESPACE TO BDVEMPP;





***************************

CREATE TABLESPACE INDX_BDVEMPD
DATAFILE 
  '+DG_DATA' SIZE 5G AUTOEXTEND ON
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;



*********************

DROP TABLESPACE DATA_BDVEMPD INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE DATA_BDVEMPD
DATAFILE 
  '+DG_DATA' SIZE 20G AUTOEXTEND ON,
  '+DG_DATA' SIZE 20G AUTOEXTEND ON,
  '+DG_DATA' SIZE 20G AUTOEXTEND ON,
  '+DG_DATA' SIZE 20G AUTOEXTEND ON
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;





REMAP_TABLESPACE=DATA_BDVEMPD:DATA




DROP USER BDVEMPP CASCADE;

CREATE USER BDVEMPP
  IDENTIFIED BY bqsmt7aral8
  DEFAULT TABLESPACE DATA
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
GRANT CONNECT TO BDVEMPP;
GRANT DATAPUMP_EXP_FULL_DATABASE TO BDVEMPP;
GRANT RESOURCE TO BDVEMPP;
ALTER USER BDVEMPP DEFAULT ROLE NONE;
GRANT ADVISOR TO BDVEMPP;
GRANT CREATE ANY INDEX TO BDVEMPP;
GRANT CREATE LIBRARY TO BDVEMPP;
GRANT CREATE MATERIALIZED VIEW TO BDVEMPP;
GRANT CREATE PROCEDURE TO BDVEMPP;
GRANT CREATE PUBLIC DATABASE LINK TO BDVEMPP;
GRANT CREATE PUBLIC SYNONYM TO BDVEMPP;
GRANT CREATE SEQUENCE TO BDVEMPP;
GRANT CREATE SESSION TO BDVEMPP;
GRANT CREATE SYNONYM TO BDVEMPP;
GRANT CREATE TABLE TO BDVEMPP;
GRANT CREATE TRIGGER TO BDVEMPP;
GRANT CREATE TYPE TO BDVEMPP;
GRANT CREATE VIEW TO BDVEMPP;
GRANT DEBUG ANY PROCEDURE TO BDVEMPP;
GRANT DEBUG CONNECT SESSION TO BDVEMPP;
GRANT DROP PUBLIC DATABASE LINK TO BDVEMPP;
GRANT EXECUTE ANY PROCEDURE TO BDVEMPP;
GRANT SELECT ANY SEQUENCE TO BDVEMPP;
GRANT SELECT ANY TABLE TO BDVEMPP;
GRANT UNLIMITED TABLESPACE TO BDVEMPP;
ALTER USER BDVEMPP QUOTA UNLIMITED  ON DATA;
ALTER USER BDVEMPP QUOTA UNLIMITED  ON INDX_BDVEMPD;






----------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER BDVEMPP.REGCHEQ_TRI 
BEFORE INSERT ON BDVEMPP.REGCHEQARCHIVOS 
FOR EACH ROW
BEGIN
  SELECT REGCHEQARCHIVOS_SEQ.NEXTVAL
  INTO   :new.NUMREGISTRO
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER BDVEMPP.LOG_OPERACIONES_AI
before insert ON BDVEMPP.LOG_OPERACIONES
    for each row
DISABLE
begin
            select log_seq.nextval
            into :new.id
            from dual;
        end;
/


CREATE OR REPLACE TRIGGER BDVEMPP.RINO_LOGOPERACIONESAI
before insert ON BDVEMPP.LOG_OPERACIONES
    for each row
begin
            select RINOLOGOPERACIONES_SEQ.nextval
            into :new.id
            from dual;
        end;
/

CREATE OR REPLACE TRIGGER BDVEMPP.PLSQL_ERRORLOG_TR
  BEFORE INSERT ON "BDVEMPP"."PLSQL_ERRORLOG"
  FOR EACH ROW
DECLARE
  v_code NUMBER(10);
BEGIN
  SELECT PLSQL_ERRORLOG_SQ.NEXTVAL INTO v_code FROM DUAL;
  :NEW.ID := v_code;
END;
/

CREATE OR REPLACE TRIGGER BDVEMPP.INSERT_NOTIF
BEFORE INSERT ON BDVEMPP.NOTIFICACIONES
FOR EACH ROW
DECLARE
ID_NOTIFN NUMBER(8);
ID_NOTIFD VARCHAR2(8);

BEGIN
SELECT BDVEMPP.SEQ_NOTIFICACIONES.NEXTVAL INTO ID_NOTIFN FROM DUAL;
ID_NOTIFD := TRIM(TO_CHAR(ID_NOTIFN,'00000000'));
SELECT ID_NOTIFD INTO :NEW.ID_NOTIFICACION FROM DUAL;
END;
/


CREATE OR REPLACE TRIGGER BDVEMPP.token_semillasAI
before insert ON BDVEMPP.TOKEN_SEMILLAS
    for each row
begin
            select token_semillas_seq.nextval
            into :new.id
            from dual;
        end;
/



***************************************************************


grant EXECUTE on SYS.DBMS_CRYPTO to BDVEMPP;
grant EXECUTE on SYS.DBMS_DATAPUMP to BDVEMPP;
grant EXECUTE on SYS.DBMS_JOB to SEGURIDAD_INFORMATICA;
grant EXECUTE on SYS.DBMS_TRANSACTION to SEGURIDAD_INFORMATICA;
grant READ on SYS.EXPORT to BDVEMPP;
grant SELECT on SYS.DBA_DIRECTORIES to BDVEMPP;
grant SELECT on SYS.DBA_TAB_PARTITIONS to BDVEMPP;
grant SELECT on SYS.DBA_TAB_SUBPARTITIONS to BDVEMPP;
grant WRITE on SYS.EXPORT to BDVEMPP;


